// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/proxy/reconcile (interfaces: Stores,BackendResolver,UsageRecorder)
//
// Generated by this command:
//
//	mockgen -destination=mock_manager_test.go -package=reconcile github.com/afreidah/s3-orchestrator/internal/proxy/reconcile Stores,BackendResolver,UsageRecorder
//

// Package reconcile is a generated GoMock package.
package reconcile

import (
	context "context"
	reflect "reflect"

	backend "github.com/afreidah/s3-orchestrator/internal/backend"
	s3op "github.com/afreidah/s3-orchestrator/internal/s3op"
	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	gomock "go.uber.org/mock/gomock"
)

// MockStores is a mock of Stores interface.
type MockStores struct {
	ctrl     *gomock.Controller
	recorder *MockStoresMockRecorder
	isgomock struct{}
}

// MockStoresMockRecorder is the mock recorder for MockStores.
type MockStoresMockRecorder struct {
	mock *MockStores
}

// NewMockStores creates a new mock instance.
func NewMockStores(ctrl *gomock.Controller) *MockStores {
	mock := &MockStores{ctrl: ctrl}
	mock.recorder = &MockStoresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStores) EXPECT() *MockStoresMockRecorder {
	return m.recorder
}

// DeleteObjectLocation mocks base method.
func (m *MockStores) DeleteObjectLocation(ctx context.Context, key, backendName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectLocation", ctx, key, backendName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectLocation indicates an expected call of DeleteObjectLocation.
func (mr *MockStoresMockRecorder) DeleteObjectLocation(ctx, key, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectLocation", reflect.TypeOf((*MockStores)(nil).DeleteObjectLocation), ctx, key, backendName)
}

// GetAllObjectLocations mocks base method.
func (m *MockStores) GetAllObjectLocations(ctx context.Context, key string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjectLocations", ctx, key)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllObjectLocations indicates an expected call of GetAllObjectLocations.
func (mr *MockStoresMockRecorder) GetAllObjectLocations(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjectLocations", reflect.TypeOf((*MockStores)(nil).GetAllObjectLocations), ctx, key)
}

// ImportObject mocks base method.
func (m *MockStores) ImportObject(ctx context.Context, req *core.ImportObjectRequest) (core.ImportOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportObject", ctx, req)
	ret0, _ := ret[0].(core.ImportOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportObject indicates an expected call of ImportObject.
func (mr *MockStoresMockRecorder) ImportObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportObject", reflect.TypeOf((*MockStores)(nil).ImportObject), ctx, req)
}

// ListObjectsByBackendKeyAsc mocks base method.
func (m *MockStores) ListObjectsByBackendKeyAsc(ctx context.Context, backendName, afterKey string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackendKeyAsc", ctx, backendName, afterKey, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackendKeyAsc indicates an expected call of ListObjectsByBackendKeyAsc.
func (mr *MockStoresMockRecorder) ListObjectsByBackendKeyAsc(ctx, backendName, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackendKeyAsc", reflect.TypeOf((*MockStores)(nil).ListObjectsByBackendKeyAsc), ctx, backendName, afterKey, limit)
}

// SweepStaleCleanupQueueRows mocks base method.
func (m *MockStores) SweepStaleCleanupQueueRows(ctx context.Context, storageKey, backendName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepStaleCleanupQueueRows", ctx, storageKey, backendName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepStaleCleanupQueueRows indicates an expected call of SweepStaleCleanupQueueRows.
func (mr *MockStoresMockRecorder) SweepStaleCleanupQueueRows(ctx, storageKey, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepStaleCleanupQueueRows", reflect.TypeOf((*MockStores)(nil).SweepStaleCleanupQueueRows), ctx, storageKey, backendName)
}

// MockBackendResolver is a mock of BackendResolver interface.
type MockBackendResolver struct {
	ctrl     *gomock.Controller
	recorder *MockBackendResolverMockRecorder
	isgomock struct{}
}

// MockBackendResolverMockRecorder is the mock recorder for MockBackendResolver.
type MockBackendResolverMockRecorder struct {
	mock *MockBackendResolver
}

// NewMockBackendResolver creates a new mock instance.
func NewMockBackendResolver(ctrl *gomock.Controller) *MockBackendResolver {
	mock := &MockBackendResolver{ctrl: ctrl}
	mock.recorder = &MockBackendResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendResolver) EXPECT() *MockBackendResolverMockRecorder {
	return m.recorder
}

// GetBackend mocks base method.
func (m *MockBackendResolver) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockBackendResolverMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockBackendResolver)(nil).GetBackend), name)
}

// MockUsageRecorder is a mock of UsageRecorder interface.
type MockUsageRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockUsageRecorderMockRecorder
	isgomock struct{}
}

// MockUsageRecorderMockRecorder is the mock recorder for MockUsageRecorder.
type MockUsageRecorderMockRecorder struct {
	mock *MockUsageRecorder
}

// NewMockUsageRecorder creates a new mock instance.
func NewMockUsageRecorder(ctrl *gomock.Controller) *MockUsageRecorder {
	mock := &MockUsageRecorder{ctrl: ctrl}
	mock.recorder = &MockUsageRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageRecorder) EXPECT() *MockUsageRecorderMockRecorder {
	return m.recorder
}

// APICalls mocks base method.
func (m *MockUsageRecorder) APICalls(op s3op.Operation, backendName string, n int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "APICalls", op, backendName, n)
}

// APICalls indicates an expected call of APICalls.
func (mr *MockUsageRecorderMockRecorder) APICalls(op, backendName, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APICalls", reflect.TypeOf((*MockUsageRecorder)(nil).APICalls), op, backendName, n)
}

// Allow mocks base method.
func (m *MockUsageRecorder) Allow(backendName string, ops []s3op.Operation, egress, ingress int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", backendName, ops, egress, ingress)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockUsageRecorderMockRecorder) Allow(backendName, ops, egress, ingress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockUsageRecorder)(nil).Allow), backendName, ops, egress, ingress)
}
