// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/store/storetest (interfaces: MetadataStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=storetest github.com/afreidah/s3-orchestrator/internal/store/storetest MetadataStore
//

package storetest

import (
	context "context"
	reflect "reflect"
	time "time"

	config "github.com/afreidah/s3-orchestrator/internal/config"
	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataStore is a mock of MetadataStore interface.
type MockMetadataStore struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataStoreMockRecorder
	isgomock struct{}
}

// MockMetadataStoreMockRecorder is the mock recorder for MockMetadataStore.
type MockMetadataStoreMockRecorder struct {
	mock *MockMetadataStore
}

// NewMockMetadataStore creates a new mock instance.
func NewMockMetadataStore(ctrl *gomock.Controller) *MockMetadataStore {
	mock := &MockMetadataStore{ctrl: ctrl}
	mock.recorder = &MockMetadataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataStore) EXPECT() *MockMetadataStoreMockRecorder {
	return m.recorder
}

// BackendObjectStats mocks base method.
func (m *MockMetadataStore) BackendObjectStats(ctx context.Context, backendName string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendObjectStats", ctx, backendName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BackendObjectStats indicates an expected call of BackendObjectStats.
func (mr *MockMetadataStoreMockRecorder) BackendObjectStats(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendObjectStats", reflect.TypeOf((*MockMetadataStore)(nil).BackendObjectStats), ctx, backendName)
}

// ClaimPendingCleanups mocks base method.
func (m *MockMetadataStore) ClaimPendingCleanups(ctx context.Context, limit int, instanceID string, graceCutoff time.Time) ([]core.CleanupItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingCleanups", ctx, limit, instanceID, graceCutoff)
	ret0, _ := ret[0].([]core.CleanupItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingCleanups indicates an expected call of ClaimPendingCleanups.
func (mr *MockMetadataStoreMockRecorder) ClaimPendingCleanups(ctx, limit, instanceID, graceCutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingCleanups", reflect.TypeOf((*MockMetadataStore)(nil).ClaimPendingCleanups), ctx, limit, instanceID, graceCutoff)
}

// CleanupDLQDepth mocks base method.
func (m *MockMetadataStore) CleanupDLQDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupDLQDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupDLQDepth indicates an expected call of CleanupDLQDepth.
func (mr *MockMetadataStoreMockRecorder) CleanupDLQDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupDLQDepth", reflect.TypeOf((*MockMetadataStore)(nil).CleanupDLQDepth), ctx)
}

// CleanupQueueDepth mocks base method.
func (m *MockMetadataStore) CleanupQueueDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupQueueDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupQueueDepth indicates an expected call of CleanupQueueDepth.
func (mr *MockMetadataStoreMockRecorder) CleanupQueueDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupQueueDepth", reflect.TypeOf((*MockMetadataStore)(nil).CleanupQueueDepth), ctx)
}

// Close mocks base method.
func (m *MockMetadataStore) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMetadataStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMetadataStore)(nil).Close))
}

// CommitCompanionCopy mocks base method.
func (m *MockMetadataStore) CommitCompanionCopy(ctx context.Context, p *core.PendingObject) (core.CompanionCommitResult, []core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitCompanionCopy", ctx, p)
	ret0, _ := ret[0].(core.CompanionCommitResult)
	ret1, _ := ret[1].([]core.DeletedCopy)
	ret2, _ := ret[2].(core.QuotaDeltas)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CommitCompanionCopy indicates an expected call of CommitCompanionCopy.
func (mr *MockMetadataStoreMockRecorder) CommitCompanionCopy(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitCompanionCopy", reflect.TypeOf((*MockMetadataStore)(nil).CommitCompanionCopy), ctx, p)
}

// CompleteCleanupItem mocks base method.
func (m *MockMetadataStore) CompleteCleanupItem(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCleanupItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteCleanupItem indicates an expected call of CompleteCleanupItem.
func (mr *MockMetadataStoreMockRecorder) CompleteCleanupItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCleanupItem", reflect.TypeOf((*MockMetadataStore)(nil).CompleteCleanupItem), ctx, id)
}

// CompleteNotification mocks base method.
func (m *MockMetadataStore) CompleteNotification(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteNotification", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteNotification indicates an expected call of CompleteNotification.
func (mr *MockMetadataStoreMockRecorder) CompleteNotification(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteNotification", reflect.TypeOf((*MockMetadataStore)(nil).CompleteNotification), ctx, id)
}

// CompressionStats mocks base method.
func (m *MockMetadataStore) CompressionStats(ctx context.Context) (map[string]core.CompressionStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressionStats", ctx)
	ret0, _ := ret[0].(map[string]core.CompressionStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompressionStats indicates an expected call of CompressionStats.
func (mr *MockMetadataStoreMockRecorder) CompressionStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressionStats", reflect.TypeOf((*MockMetadataStore)(nil).CompressionStats), ctx)
}

// CountActiveMultipartUploads mocks base method.
func (m *MockMetadataStore) CountActiveMultipartUploads(ctx context.Context, bucketPrefix string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveMultipartUploads", ctx, bucketPrefix)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveMultipartUploads indicates an expected call of CountActiveMultipartUploads.
func (mr *MockMetadataStoreMockRecorder) CountActiveMultipartUploads(ctx, bucketPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveMultipartUploads", reflect.TypeOf((*MockMetadataStore)(nil).CountActiveMultipartUploads), ctx, bucketPrefix)
}

// CountObjectTags mocks base method.
func (m *MockMetadataStore) CountObjectTags(ctx context.Context, key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountObjectTags", ctx, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountObjectTags indicates an expected call of CountObjectTags.
func (mr *MockMetadataStoreMockRecorder) CountObjectTags(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountObjectTags", reflect.TypeOf((*MockMetadataStore)(nil).CountObjectTags), ctx, key)
}

// CountObjectsByPrefix mocks base method.
func (m *MockMetadataStore) CountObjectsByPrefix(ctx context.Context, prefix string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountObjectsByPrefix", ctx, prefix)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountObjectsByPrefix indicates an expected call of CountObjectsByPrefix.
func (mr *MockMetadataStoreMockRecorder) CountObjectsByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountObjectsByPrefix", reflect.TypeOf((*MockMetadataStore)(nil).CountObjectsByPrefix), ctx, prefix)
}

// CountOverReplicatedObjects mocks base method.
func (m *MockMetadataStore) CountOverReplicatedObjects(ctx context.Context, factor int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOverReplicatedObjects", ctx, factor)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOverReplicatedObjects indicates an expected call of CountOverReplicatedObjects.
func (mr *MockMetadataStoreMockRecorder) CountOverReplicatedObjects(ctx, factor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOverReplicatedObjects", reflect.TypeOf((*MockMetadataStore)(nil).CountOverReplicatedObjects), ctx, factor)
}

// CountScrubCandidatesOnBackends mocks base method.
func (m *MockMetadataStore) CountScrubCandidatesOnBackends(ctx context.Context, backends []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountScrubCandidatesOnBackends", ctx, backends)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountScrubCandidatesOnBackends indicates an expected call of CountScrubCandidatesOnBackends.
func (mr *MockMetadataStoreMockRecorder) CountScrubCandidatesOnBackends(ctx, backends any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountScrubCandidatesOnBackends", reflect.TypeOf((*MockMetadataStore)(nil).CountScrubCandidatesOnBackends), ctx, backends)
}

// CountUnencryptedLocations mocks base method.
func (m *MockMetadataStore) CountUnencryptedLocations(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnencryptedLocations", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnencryptedLocations indicates an expected call of CountUnencryptedLocations.
func (mr *MockMetadataStoreMockRecorder) CountUnencryptedLocations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnencryptedLocations", reflect.TypeOf((*MockMetadataStore)(nil).CountUnencryptedLocations), ctx)
}

// CreateBucket mocks base method.
func (m *MockMetadataStore) CreateBucket(ctx context.Context, b *core.Bucket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockMetadataStoreMockRecorder) CreateBucket(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockMetadataStore)(nil).CreateBucket), ctx, b)
}

// CreateCredential mocks base method.
func (m *MockMetadataStore) CreateCredential(ctx context.Context, c *core.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockMetadataStoreMockRecorder) CreateCredential(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockMetadataStore)(nil).CreateCredential), ctx, c)
}

// CreateGrant mocks base method.
func (m *MockMetadataStore) CreateGrant(ctx context.Context, g *core.Grant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGrant", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGrant indicates an expected call of CreateGrant.
func (mr *MockMetadataStoreMockRecorder) CreateGrant(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGrant", reflect.TypeOf((*MockMetadataStore)(nil).CreateGrant), ctx, g)
}

// CreateMultipartUpload mocks base method.
func (m *MockMetadataStore) CreateMultipartUpload(ctx context.Context, params *core.CreateMultipartUploadParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockMetadataStoreMockRecorder) CreateMultipartUpload(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockMetadataStore)(nil).CreateMultipartUpload), ctx, params)
}

// CreateUser mocks base method.
func (m *MockMetadataStore) CreateUser(ctx context.Context, u *core.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockMetadataStoreMockRecorder) CreateUser(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockMetadataStore)(nil).CreateUser), ctx, u)
}

// DecrementOrphanBytes mocks base method.
func (m *MockMetadataStore) DecrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementOrphanBytes indicates an expected call of DecrementOrphanBytes.
func (mr *MockMetadataStoreMockRecorder) DecrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementOrphanBytes", reflect.TypeOf((*MockMetadataStore)(nil).DecrementOrphanBytes), ctx, backendName, amount)
}

// DeleteBackendData mocks base method.
func (m *MockMetadataStore) DeleteBackendData(ctx context.Context, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackendData", ctx, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackendData indicates an expected call of DeleteBackendData.
func (mr *MockMetadataStoreMockRecorder) DeleteBackendData(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackendData", reflect.TypeOf((*MockMetadataStore)(nil).DeleteBackendData), ctx, backendName)
}

// DeleteBucket mocks base method.
func (m *MockMetadataStore) DeleteBucket(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBucket", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBucket indicates an expected call of DeleteBucket.
func (mr *MockMetadataStoreMockRecorder) DeleteBucket(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBucket", reflect.TypeOf((*MockMetadataStore)(nil).DeleteBucket), ctx, name)
}

// DeleteCredential mocks base method.
func (m *MockMetadataStore) DeleteCredential(ctx context.Context, accessKeyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", ctx, accessKeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockMetadataStoreMockRecorder) DeleteCredential(ctx, accessKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockMetadataStore)(nil).DeleteCredential), ctx, accessKeyID)
}

// DeleteGrant mocks base method.
func (m *MockMetadataStore) DeleteGrant(ctx context.Context, userID string, r core.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGrant", ctx, userID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGrant indicates an expected call of DeleteGrant.
func (mr *MockMetadataStoreMockRecorder) DeleteGrant(ctx, userID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGrant", reflect.TypeOf((*MockMetadataStore)(nil).DeleteGrant), ctx, userID, r)
}

// DeleteMultipartUpload mocks base method.
func (m *MockMetadataStore) DeleteMultipartUpload(ctx context.Context, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultipartUpload", ctx, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultipartUpload indicates an expected call of DeleteMultipartUpload.
func (mr *MockMetadataStoreMockRecorder) DeleteMultipartUpload(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultipartUpload", reflect.TypeOf((*MockMetadataStore)(nil).DeleteMultipartUpload), ctx, uploadID)
}

// DeleteObject mocks base method.
func (m *MockMetadataStore) DeleteObject(ctx context.Context, key string) ([]core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(core.QuotaDeltas)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockMetadataStoreMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockMetadataStore)(nil).DeleteObject), ctx, key)
}

// DeleteObjectLocation mocks base method.
func (m *MockMetadataStore) DeleteObjectLocation(ctx context.Context, key, backendName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectLocation", ctx, key, backendName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectLocation indicates an expected call of DeleteObjectLocation.
func (mr *MockMetadataStoreMockRecorder) DeleteObjectLocation(ctx, key, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectLocation", reflect.TypeOf((*MockMetadataStore)(nil).DeleteObjectLocation), ctx, key, backendName)
}

// DeleteObjectTags mocks base method.
func (m *MockMetadataStore) DeleteObjectTags(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectTags", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectTags indicates an expected call of DeleteObjectTags.
func (mr *MockMetadataStoreMockRecorder) DeleteObjectTags(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectTags", reflect.TypeOf((*MockMetadataStore)(nil).DeleteObjectTags), ctx, key)
}

// DeleteObjectsBatch mocks base method.
func (m *MockMetadataStore) DeleteObjectsBatch(ctx context.Context, keys []string) (map[string][]core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectsBatch", ctx, keys)
	ret0, _ := ret[0].(map[string][]core.DeletedCopy)
	ret1, _ := ret[1].(core.QuotaDeltas)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteObjectsBatch indicates an expected call of DeleteObjectsBatch.
func (mr *MockMetadataStoreMockRecorder) DeleteObjectsBatch(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectsBatch", reflect.TypeOf((*MockMetadataStore)(nil).DeleteObjectsBatch), ctx, keys)
}

// DeletePending mocks base method.
func (m *MockMetadataStore) DeletePending(ctx context.Context, intentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePending", ctx, intentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePending indicates an expected call of DeletePending.
func (mr *MockMetadataStoreMockRecorder) DeletePending(ctx, intentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePending", reflect.TypeOf((*MockMetadataStore)(nil).DeletePending), ctx, intentID)
}

// DeletePendingByBackend mocks base method.
func (m *MockMetadataStore) DeletePendingByBackend(ctx context.Context, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingByBackend", ctx, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingByBackend indicates an expected call of DeletePendingByBackend.
func (mr *MockMetadataStoreMockRecorder) DeletePendingByBackend(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingByBackend", reflect.TypeOf((*MockMetadataStore)(nil).DeletePendingByBackend), ctx, backendName)
}

// DeleteUser mocks base method.
func (m *MockMetadataStore) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockMetadataStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockMetadataStore)(nil).DeleteUser), ctx, id)
}

// EnqueueCleanup mocks base method.
func (m *MockMetadataStore) EnqueueCleanup(ctx context.Context, c *core.CleanupRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueCleanup", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueCleanup indicates an expected call of EnqueueCleanup.
func (mr *MockMetadataStoreMockRecorder) EnqueueCleanup(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueCleanup", reflect.TypeOf((*MockMetadataStore)(nil).EnqueueCleanup), ctx, c)
}

// FlushPoolDeltas mocks base method.
func (m *MockMetadataStore) FlushPoolDeltas(ctx context.Context, backendName, period string, deltas core.PoolUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushPoolDeltas", ctx, backendName, period, deltas)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushPoolDeltas indicates an expected call of FlushPoolDeltas.
func (mr *MockMetadataStoreMockRecorder) FlushPoolDeltas(ctx, backendName, period, deltas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushPoolDeltas", reflect.TypeOf((*MockMetadataStore)(nil).FlushPoolDeltas), ctx, backendName, period, deltas)
}

// FlushUsageDeltas mocks base method.
func (m *MockMetadataStore) FlushUsageDeltas(ctx context.Context, backendName, period string, apiRequests, egressBytes, ingressBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushUsageDeltas", ctx, backendName, period, apiRequests, egressBytes, ingressBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushUsageDeltas indicates an expected call of FlushUsageDeltas.
func (mr *MockMetadataStoreMockRecorder) FlushUsageDeltas(ctx, backendName, period, apiRequests, egressBytes, ingressBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushUsageDeltas", reflect.TypeOf((*MockMetadataStore)(nil).FlushUsageDeltas), ctx, backendName, period, apiRequests, egressBytes, ingressBytes)
}

// GetActiveMultipartCounts mocks base method.
func (m *MockMetadataStore) GetActiveMultipartCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMultipartCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMultipartCounts indicates an expected call of GetActiveMultipartCounts.
func (mr *MockMetadataStoreMockRecorder) GetActiveMultipartCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMultipartCounts", reflect.TypeOf((*MockMetadataStore)(nil).GetActiveMultipartCounts), ctx)
}

// GetAllObjectLocations mocks base method.
func (m *MockMetadataStore) GetAllObjectLocations(ctx context.Context, key string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjectLocations", ctx, key)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllObjectLocations indicates an expected call of GetAllObjectLocations.
func (mr *MockMetadataStoreMockRecorder) GetAllObjectLocations(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjectLocations", reflect.TypeOf((*MockMetadataStore)(nil).GetAllObjectLocations), ctx, key)
}

// GetLeastRecentlyScrubbedObjects mocks base method.
func (m *MockMetadataStore) GetLeastRecentlyScrubbedObjects(ctx context.Context, limit int, backends []string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeastRecentlyScrubbedObjects", ctx, limit, backends)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeastRecentlyScrubbedObjects indicates an expected call of GetLeastRecentlyScrubbedObjects.
func (mr *MockMetadataStoreMockRecorder) GetLeastRecentlyScrubbedObjects(ctx, limit, backends any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeastRecentlyScrubbedObjects", reflect.TypeOf((*MockMetadataStore)(nil).GetLeastRecentlyScrubbedObjects), ctx, limit, backends)
}

// GetMultipartUpload mocks base method.
func (m *MockMetadataStore) GetMultipartUpload(ctx context.Context, uploadID string) (*core.MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMultipartUpload", ctx, uploadID)
	ret0, _ := ret[0].(*core.MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMultipartUpload indicates an expected call of GetMultipartUpload.
func (mr *MockMetadataStoreMockRecorder) GetMultipartUpload(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMultipartUpload", reflect.TypeOf((*MockMetadataStore)(nil).GetMultipartUpload), ctx, uploadID)
}

// GetMultipartUploadsByBackend mocks base method.
func (m *MockMetadataStore) GetMultipartUploadsByBackend(ctx context.Context, backendName string) ([]core.MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMultipartUploadsByBackend", ctx, backendName)
	ret0, _ := ret[0].([]core.MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMultipartUploadsByBackend indicates an expected call of GetMultipartUploadsByBackend.
func (mr *MockMetadataStoreMockRecorder) GetMultipartUploadsByBackend(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMultipartUploadsByBackend", reflect.TypeOf((*MockMetadataStore)(nil).GetMultipartUploadsByBackend), ctx, backendName)
}

// GetObjectBackendsForKeys mocks base method.
func (m *MockMetadataStore) GetObjectBackendsForKeys(ctx context.Context, keys []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectBackendsForKeys", ctx, keys)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectBackendsForKeys indicates an expected call of GetObjectBackendsForKeys.
func (mr *MockMetadataStoreMockRecorder) GetObjectBackendsForKeys(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectBackendsForKeys", reflect.TypeOf((*MockMetadataStore)(nil).GetObjectBackendsForKeys), ctx, keys)
}

// GetObjectCounts mocks base method.
func (m *MockMetadataStore) GetObjectCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectCounts indicates an expected call of GetObjectCounts.
func (mr *MockMetadataStoreMockRecorder) GetObjectCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectCounts", reflect.TypeOf((*MockMetadataStore)(nil).GetObjectCounts), ctx)
}

// GetObjectTags mocks base method.
func (m *MockMetadataStore) GetObjectTags(ctx context.Context, key string) ([]core.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTags", ctx, key)
	ret0, _ := ret[0].([]core.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTags indicates an expected call of GetObjectTags.
func (mr *MockMetadataStoreMockRecorder) GetObjectTags(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTags", reflect.TypeOf((*MockMetadataStore)(nil).GetObjectTags), ctx, key)
}

// GetObjectsWithoutHash mocks base method.
func (m *MockMetadataStore) GetObjectsWithoutHash(ctx context.Context, limit, offset int, backend string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectsWithoutHash", ctx, limit, offset, backend)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectsWithoutHash indicates an expected call of GetObjectsWithoutHash.
func (mr *MockMetadataStoreMockRecorder) GetObjectsWithoutHash(ctx, limit, offset, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectsWithoutHash", reflect.TypeOf((*MockMetadataStore)(nil).GetObjectsWithoutHash), ctx, limit, offset, backend)
}

// GetOverReplicatedObjects mocks base method.
func (m *MockMetadataStore) GetOverReplicatedObjects(ctx context.Context, factor, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverReplicatedObjects", ctx, factor, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverReplicatedObjects indicates an expected call of GetOverReplicatedObjects.
func (mr *MockMetadataStoreMockRecorder) GetOverReplicatedObjects(ctx, factor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverReplicatedObjects", reflect.TypeOf((*MockMetadataStore)(nil).GetOverReplicatedObjects), ctx, factor, limit)
}

// GetParts mocks base method.
func (m *MockMetadataStore) GetParts(ctx context.Context, uploadID string) ([]core.MultipartPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParts", ctx, uploadID)
	ret0, _ := ret[0].([]core.MultipartPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParts indicates an expected call of GetParts.
func (mr *MockMetadataStoreMockRecorder) GetParts(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParts", reflect.TypeOf((*MockMetadataStore)(nil).GetParts), ctx, uploadID)
}

// GetPendingCleanups mocks base method.
func (m *MockMetadataStore) GetPendingCleanups(ctx context.Context, limit int) ([]core.CleanupItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingCleanups", ctx, limit)
	ret0, _ := ret[0].([]core.CleanupItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingCleanups indicates an expected call of GetPendingCleanups.
func (mr *MockMetadataStoreMockRecorder) GetPendingCleanups(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingCleanups", reflect.TypeOf((*MockMetadataStore)(nil).GetPendingCleanups), ctx, limit)
}

// GetPendingNotifications mocks base method.
func (m *MockMetadataStore) GetPendingNotifications(ctx context.Context, limit int) ([]core.NotificationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingNotifications", ctx, limit)
	ret0, _ := ret[0].([]core.NotificationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingNotifications indicates an expected call of GetPendingNotifications.
func (mr *MockMetadataStoreMockRecorder) GetPendingNotifications(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingNotifications", reflect.TypeOf((*MockMetadataStore)(nil).GetPendingNotifications), ctx, limit)
}

// GetPoolUsageForPeriod mocks base method.
func (m *MockMetadataStore) GetPoolUsageForPeriod(ctx context.Context, period string) (map[string]core.PoolUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolUsageForPeriod", ctx, period)
	ret0, _ := ret[0].(map[string]core.PoolUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoolUsageForPeriod indicates an expected call of GetPoolUsageForPeriod.
func (mr *MockMetadataStoreMockRecorder) GetPoolUsageForPeriod(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolUsageForPeriod", reflect.TypeOf((*MockMetadataStore)(nil).GetPoolUsageForPeriod), ctx, period)
}

// GetQuotaStats mocks base method.
func (m *MockMetadataStore) GetQuotaStats(ctx context.Context) (map[string]core.QuotaStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaStats", ctx)
	ret0, _ := ret[0].(map[string]core.QuotaStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaStats indicates an expected call of GetQuotaStats.
func (mr *MockMetadataStoreMockRecorder) GetQuotaStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaStats", reflect.TypeOf((*MockMetadataStore)(nil).GetQuotaStats), ctx)
}

// GetStaleMultipartUploads mocks base method.
func (m *MockMetadataStore) GetStaleMultipartUploads(ctx context.Context, olderThan time.Duration) ([]core.MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaleMultipartUploads", ctx, olderThan)
	ret0, _ := ret[0].([]core.MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaleMultipartUploads indicates an expected call of GetStaleMultipartUploads.
func (mr *MockMetadataStoreMockRecorder) GetStaleMultipartUploads(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaleMultipartUploads", reflect.TypeOf((*MockMetadataStore)(nil).GetStaleMultipartUploads), ctx, olderThan)
}

// GetStalePending mocks base method.
func (m *MockMetadataStore) GetStalePending(ctx context.Context, olderThan time.Time, limit int) ([]core.PendingObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStalePending", ctx, olderThan, limit)
	ret0, _ := ret[0].([]core.PendingObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStalePending indicates an expected call of GetStalePending.
func (mr *MockMetadataStoreMockRecorder) GetStalePending(ctx, olderThan, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStalePending", reflect.TypeOf((*MockMetadataStore)(nil).GetStalePending), ctx, olderThan, limit)
}

// GetUnderReplicatedObjects mocks base method.
func (m *MockMetadataStore) GetUnderReplicatedObjects(ctx context.Context, factor, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnderReplicatedObjects", ctx, factor, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnderReplicatedObjects indicates an expected call of GetUnderReplicatedObjects.
func (mr *MockMetadataStoreMockRecorder) GetUnderReplicatedObjects(ctx, factor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnderReplicatedObjects", reflect.TypeOf((*MockMetadataStore)(nil).GetUnderReplicatedObjects), ctx, factor, limit)
}

// GetUnderReplicatedObjectsExcluding mocks base method.
func (m *MockMetadataStore) GetUnderReplicatedObjectsExcluding(ctx context.Context, factor, limit int, excludedBackends []string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnderReplicatedObjectsExcluding", ctx, factor, limit, excludedBackends)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnderReplicatedObjectsExcluding indicates an expected call of GetUnderReplicatedObjectsExcluding.
func (mr *MockMetadataStoreMockRecorder) GetUnderReplicatedObjectsExcluding(ctx, factor, limit, excludedBackends any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnderReplicatedObjectsExcluding", reflect.TypeOf((*MockMetadataStore)(nil).GetUnderReplicatedObjectsExcluding), ctx, factor, limit, excludedBackends)
}

// GetUnverifiedObjectCounts mocks base method.
func (m *MockMetadataStore) GetUnverifiedObjectCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnverifiedObjectCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnverifiedObjectCounts indicates an expected call of GetUnverifiedObjectCounts.
func (mr *MockMetadataStoreMockRecorder) GetUnverifiedObjectCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnverifiedObjectCounts", reflect.TypeOf((*MockMetadataStore)(nil).GetUnverifiedObjectCounts), ctx)
}

// GetUsageForPeriod mocks base method.
func (m *MockMetadataStore) GetUsageForPeriod(ctx context.Context, period string) (map[string]core.UsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsageForPeriod", ctx, period)
	ret0, _ := ret[0].(map[string]core.UsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsageForPeriod indicates an expected call of GetUsageForPeriod.
func (mr *MockMetadataStoreMockRecorder) GetUsageForPeriod(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsageForPeriod", reflect.TypeOf((*MockMetadataStore)(nil).GetUsageForPeriod), ctx, period)
}

// ImportObject mocks base method.
func (m *MockMetadataStore) ImportObject(ctx context.Context, req *core.ImportObjectRequest) (core.ImportOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportObject", ctx, req)
	ret0, _ := ret[0].(core.ImportOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportObject indicates an expected call of ImportObject.
func (mr *MockMetadataStoreMockRecorder) ImportObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportObject", reflect.TypeOf((*MockMetadataStore)(nil).ImportObject), ctx, req)
}

// IncrementOrphanBytes mocks base method.
func (m *MockMetadataStore) IncrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOrphanBytes indicates an expected call of IncrementOrphanBytes.
func (mr *MockMetadataStoreMockRecorder) IncrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOrphanBytes", reflect.TypeOf((*MockMetadataStore)(nil).IncrementOrphanBytes), ctx, backendName, amount)
}

// InsertNotification mocks base method.
func (m *MockMetadataStore) InsertNotification(ctx context.Context, eventType, payload, endpointURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertNotification", ctx, eventType, payload, endpointURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertNotification indicates an expected call of InsertNotification.
func (mr *MockMetadataStoreMockRecorder) InsertNotification(ctx, eventType, payload, endpointURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertNotification", reflect.TypeOf((*MockMetadataStore)(nil).InsertNotification), ctx, eventType, payload, endpointURL)
}

// InsertPendingIfFits mocks base method.
func (m *MockMetadataStore) InsertPendingIfFits(ctx context.Context, p *core.PendingObject) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPendingIfFits", ctx, p)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPendingIfFits indicates an expected call of InsertPendingIfFits.
func (mr *MockMetadataStoreMockRecorder) InsertPendingIfFits(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPendingIfFits", reflect.TypeOf((*MockMetadataStore)(nil).InsertPendingIfFits), ctx, p)
}

// IntegrityCoverage mocks base method.
func (m *MockMetadataStore) IntegrityCoverage(ctx context.Context, reachable []string) (core.CoverageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntegrityCoverage", ctx, reachable)
	ret0, _ := ret[0].(core.CoverageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntegrityCoverage indicates an expected call of IntegrityCoverage.
func (mr *MockMetadataStoreMockRecorder) IntegrityCoverage(ctx, reachable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntegrityCoverage", reflect.TypeOf((*MockMetadataStore)(nil).IntegrityCoverage), ctx, reachable)
}

// ListAllEncryptedLocations mocks base method.
func (m *MockMetadataStore) ListAllEncryptedLocations(ctx context.Context, limit int, after core.Cursor, backend string) ([]core.DecryptableLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllEncryptedLocations", ctx, limit, after, backend)
	ret0, _ := ret[0].([]core.DecryptableLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllEncryptedLocations indicates an expected call of ListAllEncryptedLocations.
func (mr *MockMetadataStoreMockRecorder) ListAllEncryptedLocations(ctx, limit, after, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllEncryptedLocations", reflect.TypeOf((*MockMetadataStore)(nil).ListAllEncryptedLocations), ctx, limit, after, backend)
}

// ListBackendQuotaUsage mocks base method.
func (m *MockMetadataStore) ListBackendQuotaUsage(ctx context.Context) ([]core.BackendQuotaUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackendQuotaUsage", ctx)
	ret0, _ := ret[0].([]core.BackendQuotaUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackendQuotaUsage indicates an expected call of ListBackendQuotaUsage.
func (mr *MockMetadataStoreMockRecorder) ListBackendQuotaUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackendQuotaUsage", reflect.TypeOf((*MockMetadataStore)(nil).ListBackendQuotaUsage), ctx)
}

// ListBuckets mocks base method.
func (m *MockMetadataStore) ListBuckets(ctx context.Context) ([]core.Bucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuckets", ctx)
	ret0, _ := ret[0].([]core.Bucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuckets indicates an expected call of ListBuckets.
func (mr *MockMetadataStoreMockRecorder) ListBuckets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuckets", reflect.TypeOf((*MockMetadataStore)(nil).ListBuckets), ctx)
}

// ListCleanupDLQ mocks base method.
func (m *MockMetadataStore) ListCleanupDLQ(ctx context.Context, backend string, limit int) ([]core.CleanupDLQItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCleanupDLQ", ctx, backend, limit)
	ret0, _ := ret[0].([]core.CleanupDLQItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCleanupDLQ indicates an expected call of ListCleanupDLQ.
func (mr *MockMetadataStoreMockRecorder) ListCleanupDLQ(ctx, backend, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCleanupDLQ", reflect.TypeOf((*MockMetadataStore)(nil).ListCleanupDLQ), ctx, backend, limit)
}

// ListCompressedLocations mocks base method.
func (m *MockMetadataStore) ListCompressedLocations(ctx context.Context, limit int, after core.Cursor, backend string) ([]core.RewritableLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompressedLocations", ctx, limit, after, backend)
	ret0, _ := ret[0].([]core.RewritableLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompressedLocations indicates an expected call of ListCompressedLocations.
func (mr *MockMetadataStoreMockRecorder) ListCompressedLocations(ctx, limit, after, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompressedLocations", reflect.TypeOf((*MockMetadataStore)(nil).ListCompressedLocations), ctx, limit, after, backend)
}

// ListCredentials mocks base method.
func (m *MockMetadataStore) ListCredentials(ctx context.Context) ([]core.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx)
	ret0, _ := ret[0].([]core.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockMetadataStoreMockRecorder) ListCredentials(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockMetadataStore)(nil).ListCredentials), ctx)
}

// ListDirectoryChildren mocks base method.
func (m *MockMetadataStore) ListDirectoryChildren(ctx context.Context, prefix, startAfter string, maxKeys int) (*core.DirectoryListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDirectoryChildren", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.DirectoryListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDirectoryChildren indicates an expected call of ListDirectoryChildren.
func (mr *MockMetadataStoreMockRecorder) ListDirectoryChildren(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDirectoryChildren", reflect.TypeOf((*MockMetadataStore)(nil).ListDirectoryChildren), ctx, prefix, startAfter, maxKeys)
}

// ListEncryptedLocations mocks base method.
func (m *MockMetadataStore) ListEncryptedLocations(ctx context.Context, keyID string, limit, offset int) ([]core.EncryptedLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEncryptedLocations", ctx, keyID, limit, offset)
	ret0, _ := ret[0].([]core.EncryptedLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEncryptedLocations indicates an expected call of ListEncryptedLocations.
func (mr *MockMetadataStoreMockRecorder) ListEncryptedLocations(ctx, keyID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEncryptedLocations", reflect.TypeOf((*MockMetadataStore)(nil).ListEncryptedLocations), ctx, keyID, limit, offset)
}

// ListExpiredObjects mocks base method.
func (m *MockMetadataStore) ListExpiredObjects(ctx context.Context, q core.ExpiredObjectsQuery) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredObjects", ctx, q)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredObjects indicates an expected call of ListExpiredObjects.
func (mr *MockMetadataStoreMockRecorder) ListExpiredObjects(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredObjects", reflect.TypeOf((*MockMetadataStore)(nil).ListExpiredObjects), ctx, q)
}

// ListGrants mocks base method.
func (m *MockMetadataStore) ListGrants(ctx context.Context) ([]core.Grant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGrants", ctx)
	ret0, _ := ret[0].([]core.Grant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGrants indicates an expected call of ListGrants.
func (mr *MockMetadataStoreMockRecorder) ListGrants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGrants", reflect.TypeOf((*MockMetadataStore)(nil).ListGrants), ctx)
}

// ListMultipartUploads mocks base method.
func (m *MockMetadataStore) ListMultipartUploads(ctx context.Context, prefix string, maxUploads int) ([]core.MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMultipartUploads", ctx, prefix, maxUploads)
	ret0, _ := ret[0].([]core.MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMultipartUploads indicates an expected call of ListMultipartUploads.
func (mr *MockMetadataStoreMockRecorder) ListMultipartUploads(ctx, prefix, maxUploads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMultipartUploads", reflect.TypeOf((*MockMetadataStore)(nil).ListMultipartUploads), ctx, prefix, maxUploads)
}

// ListObjects mocks base method.
func (m *MockMetadataStore) ListObjects(ctx context.Context, prefix, startAfter string, maxKeys int) (*core.ListObjectsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListObjectsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockMetadataStoreMockRecorder) ListObjects(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockMetadataStore)(nil).ListObjects), ctx, prefix, startAfter, maxKeys)
}

// ListObjectsByBackend mocks base method.
func (m *MockMetadataStore) ListObjectsByBackend(ctx context.Context, backendName string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackend", ctx, backendName, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackend indicates an expected call of ListObjectsByBackend.
func (mr *MockMetadataStoreMockRecorder) ListObjectsByBackend(ctx, backendName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackend", reflect.TypeOf((*MockMetadataStore)(nil).ListObjectsByBackend), ctx, backendName, limit)
}

// ListObjectsByBackendKeyAsc mocks base method.
func (m *MockMetadataStore) ListObjectsByBackendKeyAsc(ctx context.Context, backendName, afterKey string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackendKeyAsc", ctx, backendName, afterKey, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackendKeyAsc indicates an expected call of ListObjectsByBackendKeyAsc.
func (mr *MockMetadataStoreMockRecorder) ListObjectsByBackendKeyAsc(ctx, backendName, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackendKeyAsc", reflect.TypeOf((*MockMetadataStore)(nil).ListObjectsByBackendKeyAsc), ctx, backendName, afterKey, limit)
}

// ListObjectsDelimited mocks base method.
func (m *MockMetadataStore) ListObjectsDelimited(ctx context.Context, prefix, delimiter, startAfter string, maxKeys int) (*core.ListDelimitedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsDelimited", ctx, prefix, delimiter, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListDelimitedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsDelimited indicates an expected call of ListObjectsDelimited.
func (mr *MockMetadataStoreMockRecorder) ListObjectsDelimited(ctx, prefix, delimiter, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsDelimited", reflect.TypeOf((*MockMetadataStore)(nil).ListObjectsDelimited), ctx, prefix, delimiter, startAfter, maxKeys)
}

// ListUncompressedLocations mocks base method.
func (m *MockMetadataStore) ListUncompressedLocations(ctx context.Context, limit int, after core.Cursor, t core.CompressionThresholds, backend string) ([]core.RewritableLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUncompressedLocations", ctx, limit, after, t, backend)
	ret0, _ := ret[0].([]core.RewritableLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUncompressedLocations indicates an expected call of ListUncompressedLocations.
func (mr *MockMetadataStoreMockRecorder) ListUncompressedLocations(ctx, limit, after, t, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUncompressedLocations", reflect.TypeOf((*MockMetadataStore)(nil).ListUncompressedLocations), ctx, limit, after, t, backend)
}

// ListUnencryptedLocations mocks base method.
func (m *MockMetadataStore) ListUnencryptedLocations(ctx context.Context, limit int, after core.Cursor, backend string) ([]core.UnencryptedLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnencryptedLocations", ctx, limit, after, backend)
	ret0, _ := ret[0].([]core.UnencryptedLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnencryptedLocations indicates an expected call of ListUnencryptedLocations.
func (mr *MockMetadataStoreMockRecorder) ListUnencryptedLocations(ctx, limit, after, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnencryptedLocations", reflect.TypeOf((*MockMetadataStore)(nil).ListUnencryptedLocations), ctx, limit, after, backend)
}

// ListUsers mocks base method.
func (m *MockMetadataStore) ListUsers(ctx context.Context) ([]core.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]core.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockMetadataStoreMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockMetadataStore)(nil).ListUsers), ctx)
}

// MarkObjectCompressed mocks base method.
func (m *MockMetadataStore) MarkObjectCompressed(ctx context.Context, u *core.CompressedUpdate, previousSize int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkObjectCompressed", ctx, u, previousSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkObjectCompressed indicates an expected call of MarkObjectCompressed.
func (mr *MockMetadataStoreMockRecorder) MarkObjectCompressed(ctx, u, previousSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkObjectCompressed", reflect.TypeOf((*MockMetadataStore)(nil).MarkObjectCompressed), ctx, u, previousSize)
}

// MarkObjectDecrypted mocks base method.
func (m *MockMetadataStore) MarkObjectDecrypted(ctx context.Context, u *core.DecryptedUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkObjectDecrypted", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkObjectDecrypted indicates an expected call of MarkObjectDecrypted.
func (mr *MockMetadataStoreMockRecorder) MarkObjectDecrypted(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkObjectDecrypted", reflect.TypeOf((*MockMetadataStore)(nil).MarkObjectDecrypted), ctx, u)
}

// MarkObjectEncrypted mocks base method.
func (m *MockMetadataStore) MarkObjectEncrypted(ctx context.Context, u *core.EncryptedUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkObjectEncrypted", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkObjectEncrypted indicates an expected call of MarkObjectEncrypted.
func (mr *MockMetadataStoreMockRecorder) MarkObjectEncrypted(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkObjectEncrypted", reflect.TypeOf((*MockMetadataStore)(nil).MarkObjectEncrypted), ctx, u)
}

// MarkObjectScrubbed mocks base method.
func (m *MockMetadataStore) MarkObjectScrubbed(ctx context.Context, key, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkObjectScrubbed", ctx, key, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkObjectScrubbed indicates an expected call of MarkObjectScrubbed.
func (mr *MockMetadataStoreMockRecorder) MarkObjectScrubbed(ctx, key, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkObjectScrubbed", reflect.TypeOf((*MockMetadataStore)(nil).MarkObjectScrubbed), ctx, key, backendName)
}

// MoveCleanupToDLQ mocks base method.
func (m *MockMetadataStore) MoveCleanupToDLQ(ctx context.Context, id int64, lastError string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveCleanupToDLQ", ctx, id, lastError)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveCleanupToDLQ indicates an expected call of MoveCleanupToDLQ.
func (mr *MockMetadataStoreMockRecorder) MoveCleanupToDLQ(ctx, id, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveCleanupToDLQ", reflect.TypeOf((*MockMetadataStore)(nil).MoveCleanupToDLQ), ctx, id, lastError)
}

// MoveObjectLocation mocks base method.
func (m_2 *MockMetadataStore) MoveObjectLocation(ctx context.Context, m *core.MoveLocation) (int64, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MoveObjectLocation", ctx, m)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveObjectLocation indicates an expected call of MoveObjectLocation.
func (mr *MockMetadataStoreMockRecorder) MoveObjectLocation(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveObjectLocation", reflect.TypeOf((*MockMetadataStore)(nil).MoveObjectLocation), ctx, m)
}

// PendingDepth mocks base method.
func (m *MockMetadataStore) PendingDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingDepth indicates an expected call of PendingDepth.
func (mr *MockMetadataStoreMockRecorder) PendingDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingDepth", reflect.TypeOf((*MockMetadataStore)(nil).PendingDepth), ctx)
}

// PromotePending mocks base method.
func (m *MockMetadataStore) PromotePending(ctx context.Context, p *core.PendingObject) (core.PendingPromoteResult, []core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromotePending", ctx, p)
	ret0, _ := ret[0].(core.PendingPromoteResult)
	ret1, _ := ret[1].([]core.DeletedCopy)
	ret2, _ := ret[2].(core.QuotaDeltas)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// PromotePending indicates an expected call of PromotePending.
func (mr *MockMetadataStoreMockRecorder) PromotePending(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromotePending", reflect.TypeOf((*MockMetadataStore)(nil).PromotePending), ctx, p)
}

// ReconcileUsage mocks base method.
func (m *MockMetadataStore) ReconcileUsage(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileUsage", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileUsage indicates an expected call of ReconcileUsage.
func (mr *MockMetadataStoreMockRecorder) ReconcileUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileUsage", reflect.TypeOf((*MockMetadataStore)(nil).ReconcileUsage), ctx)
}

// RecordCompressionProbe mocks base method.
func (m *MockMetadataStore) RecordCompressionProbe(ctx context.Context, probe *core.CompressionProbe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCompressionProbe", ctx, probe)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordCompressionProbe indicates an expected call of RecordCompressionProbe.
func (mr *MockMetadataStoreMockRecorder) RecordCompressionProbe(ctx, probe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCompressionProbe", reflect.TypeOf((*MockMetadataStore)(nil).RecordCompressionProbe), ctx, probe)
}

// RecordObject mocks base method.
func (m *MockMetadataStore) RecordObject(ctx context.Context, req *core.RecordObjectRequest) ([]core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordObject", ctx, req)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(core.QuotaDeltas)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecordObject indicates an expected call of RecordObject.
func (mr *MockMetadataStoreMockRecorder) RecordObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordObject", reflect.TypeOf((*MockMetadataStore)(nil).RecordObject), ctx, req)
}

// RecordObjectIdentity mocks base method.
func (m *MockMetadataStore) RecordObjectIdentity(ctx context.Context, key string, id *core.ObjectIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordObjectIdentity", ctx, key, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordObjectIdentity indicates an expected call of RecordObjectIdentity.
func (mr *MockMetadataStoreMockRecorder) RecordObjectIdentity(ctx, key, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordObjectIdentity", reflect.TypeOf((*MockMetadataStore)(nil).RecordObjectIdentity), ctx, key, id)
}

// RecordPart mocks base method.
func (m *MockMetadataStore) RecordPart(ctx context.Context, p *core.RecordPartParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPart", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPart indicates an expected call of RecordPart.
func (mr *MockMetadataStoreMockRecorder) RecordPart(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPart", reflect.TypeOf((*MockMetadataStore)(nil).RecordPart), ctx, p)
}

// RecordReplica mocks base method.
func (m *MockMetadataStore) RecordReplica(ctx context.Context, r *core.ReplicaInsert) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordReplica", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecordReplica indicates an expected call of RecordReplica.
func (mr *MockMetadataStoreMockRecorder) RecordReplica(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordReplica", reflect.TypeOf((*MockMetadataStore)(nil).RecordReplica), ctx, r)
}

// RemoveExcessCopy mocks base method.
func (m *MockMetadataStore) RemoveExcessCopy(ctx context.Context, key, backendName string, factor int) (core.RemovedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveExcessCopy", ctx, key, backendName, factor)
	ret0, _ := ret[0].(core.RemovedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveExcessCopy indicates an expected call of RemoveExcessCopy.
func (mr *MockMetadataStoreMockRecorder) RemoveExcessCopy(ctx, key, backendName, factor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveExcessCopy", reflect.TypeOf((*MockMetadataStore)(nil).RemoveExcessCopy), ctx, key, backendName, factor)
}

// RenameUser mocks base method.
func (m *MockMetadataStore) RenameUser(ctx context.Context, id, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameUser", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameUser indicates an expected call of RenameUser.
func (mr *MockMetadataStoreMockRecorder) RenameUser(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameUser", reflect.TypeOf((*MockMetadataStore)(nil).RenameUser), ctx, id, name)
}

// ReplaceObjectTags mocks base method.
func (m *MockMetadataStore) ReplaceObjectTags(ctx context.Context, key string, tags []core.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceObjectTags", ctx, key, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceObjectTags indicates an expected call of ReplaceObjectTags.
func (mr *MockMetadataStoreMockRecorder) ReplaceObjectTags(ctx, key, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceObjectTags", reflect.TypeOf((*MockMetadataStore)(nil).ReplaceObjectTags), ctx, key, tags)
}

// RequeueCleanupDLQ mocks base method.
func (m *MockMetadataStore) RequeueCleanupDLQ(ctx context.Context, backend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueCleanupDLQ", ctx, backend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequeueCleanupDLQ indicates an expected call of RequeueCleanupDLQ.
func (mr *MockMetadataStoreMockRecorder) RequeueCleanupDLQ(ctx, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueCleanupDLQ", reflect.TypeOf((*MockMetadataStore)(nil).RequeueCleanupDLQ), ctx, backend)
}

// RetryCleanupItem mocks base method.
func (m *MockMetadataStore) RetryCleanupItem(ctx context.Context, id int64, backoff time.Duration, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryCleanupItem", ctx, id, backoff, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryCleanupItem indicates an expected call of RetryCleanupItem.
func (mr *MockMetadataStoreMockRecorder) RetryCleanupItem(ctx, id, backoff, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryCleanupItem", reflect.TypeOf((*MockMetadataStore)(nil).RetryCleanupItem), ctx, id, backoff, lastError)
}

// RetryNotification mocks base method.
func (m *MockMetadataStore) RetryNotification(ctx context.Context, id int64, backoff time.Duration, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryNotification", ctx, id, backoff, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryNotification indicates an expected call of RetryNotification.
func (mr *MockMetadataStoreMockRecorder) RetryNotification(ctx, id, backoff, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryNotification", reflect.TypeOf((*MockMetadataStore)(nil).RetryNotification), ctx, id, backoff, lastError)
}

// RunMigrations mocks base method.
func (m *MockMetadataStore) RunMigrations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrations indicates an expected call of RunMigrations.
func (mr *MockMetadataStoreMockRecorder) RunMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrations", reflect.TypeOf((*MockMetadataStore)(nil).RunMigrations), ctx)
}

// SetGrant mocks base method.
func (m *MockMetadataStore) SetGrant(ctx context.Context, g *core.Grant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGrant", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGrant indicates an expected call of SetGrant.
func (mr *MockMetadataStoreMockRecorder) SetGrant(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGrant", reflect.TypeOf((*MockMetadataStore)(nil).SetGrant), ctx, g)
}

// SweepStaleCleanupQueueRows mocks base method.
func (m *MockMetadataStore) SweepStaleCleanupQueueRows(ctx context.Context, storageKey, backend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepStaleCleanupQueueRows", ctx, storageKey, backend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepStaleCleanupQueueRows indicates an expected call of SweepStaleCleanupQueueRows.
func (mr *MockMetadataStoreMockRecorder) SweepStaleCleanupQueueRows(ctx, storageKey, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepStaleCleanupQueueRows", reflect.TypeOf((*MockMetadataStore)(nil).SweepStaleCleanupQueueRows), ctx, storageKey, backend)
}

// SyncQuotaLimits mocks base method.
func (m *MockMetadataStore) SyncQuotaLimits(ctx context.Context, backends []config.BackendConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncQuotaLimits", ctx, backends)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncQuotaLimits indicates an expected call of SyncQuotaLimits.
func (mr *MockMetadataStoreMockRecorder) SyncQuotaLimits(ctx, backends any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncQuotaLimits", reflect.TypeOf((*MockMetadataStore)(nil).SyncQuotaLimits), ctx, backends)
}

// UpdateBucket mocks base method.
func (m *MockMetadataStore) UpdateBucket(ctx context.Context, b *core.Bucket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBucket", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBucket indicates an expected call of UpdateBucket.
func (mr *MockMetadataStoreMockRecorder) UpdateBucket(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBucket", reflect.TypeOf((*MockMetadataStore)(nil).UpdateBucket), ctx, b)
}

// UpdateContentHash mocks base method.
func (m *MockMetadataStore) UpdateContentHash(ctx context.Context, key, backendName, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContentHash", ctx, key, backendName, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContentHash indicates an expected call of UpdateContentHash.
func (mr *MockMetadataStoreMockRecorder) UpdateContentHash(ctx, key, backendName, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContentHash", reflect.TypeOf((*MockMetadataStore)(nil).UpdateContentHash), ctx, key, backendName, hash)
}

// UpdateEncryptionKey mocks base method.
func (m *MockMetadataStore) UpdateEncryptionKey(ctx context.Context, objectKey, backendName string, newEncryptionKey []byte, newKeyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncryptionKey", ctx, objectKey, backendName, newEncryptionKey, newKeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEncryptionKey indicates an expected call of UpdateEncryptionKey.
func (mr *MockMetadataStoreMockRecorder) UpdateEncryptionKey(ctx, objectKey, backendName, newEncryptionKey, newKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncryptionKey", reflect.TypeOf((*MockMetadataStore)(nil).UpdateEncryptionKey), ctx, objectKey, backendName, newEncryptionKey, newKeyID)
}

// VerifySchemaVersion mocks base method.
func (m *MockMetadataStore) VerifySchemaVersion(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySchemaVersion", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifySchemaVersion indicates an expected call of VerifySchemaVersion.
func (mr *MockMetadataStoreMockRecorder) VerifySchemaVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySchemaVersion", reflect.TypeOf((*MockMetadataStore)(nil).VerifySchemaVersion), ctx)
}

// WithAdvisoryLock mocks base method.
func (m *MockMetadataStore) WithAdvisoryLock(ctx context.Context, lockID int64, fn func(context.Context) error) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAdvisoryLock", ctx, lockID, fn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithAdvisoryLock indicates an expected call of WithAdvisoryLock.
func (mr *MockMetadataStoreMockRecorder) WithAdvisoryLock(ctx, lockID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAdvisoryLock", reflect.TypeOf((*MockMetadataStore)(nil).WithAdvisoryLock), ctx, lockID, fn)
}
