// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingCleanups = `-- name: ClaimPendingCleanups :many
WITH candidate AS (
    SELECT cq.id, (cq.claimed_at IS NOT NULL)::boolean AS reclaimed
    FROM cleanup_queue cq
    WHERE cq.next_retry <= NOW()
      AND cq.attempts < 10
      AND (cq.claimed_at IS NULL OR cq.claimed_at < $2::timestamptz)
    ORDER BY cq.created_at ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE cleanup_queue cq
    SET claimed_at = NOW(),
        claimed_by = $3::text
    FROM candidate c
    WHERE cq.id = c.id
    RETURNING cq.id, cq.backend_name, cq.object_key, cq.storage_key, cq.reason, cq.attempts, cq.size_bytes
)
SELECT cl.id, cl.backend_name, cl.object_key, cl.storage_key, cl.reason, cl.attempts, cl.size_bytes,
       c.reclaimed
FROM claimed cl
JOIN candidate c ON cl.id = c.id
ORDER BY cl.id
`

type ClaimPendingCleanupsParams struct {
	Limit       int32
	GraceCutoff pgtype.Timestamptz
	ClaimedBy   string
}

type ClaimPendingCleanupsRow struct {
	ID          int64
	BackendName string
	ObjectKey   string
	StorageKey  string
	Reason      string
	Attempts    int32
	SizeBytes   int64
	Reclaimed   bool
}

// Atomically claims the next batch of cleanup rows for the calling
// instance. The inner SELECT uses FOR UPDATE SKIP LOCKED so two
// concurrent claim transactions across instances return disjoint row
// sets. A row is eligible if it has never been claimed (claimed_at IS
// NULL) or its claim has aged past the grace cutoff (claimed_at <
// @grace_cutoff). The reclaimed projection lets the worker increment
// s3o_cleanup_queue_stale_claims_recovered_total per recovered row.
func (q *Queries) ClaimPendingCleanups(ctx context.Context, arg ClaimPendingCleanupsParams) ([]ClaimPendingCleanupsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingCleanups, arg.Limit, arg.GraceCutoff, arg.ClaimedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingCleanupsRow{}
	for rows.Next() {
		var i ClaimPendingCleanupsRow
		if err := rows.Scan(
			&i.ID,
			&i.BackendName,
			&i.ObjectKey,
			&i.StorageKey,
			&i.Reason,
			&i.Attempts,
			&i.SizeBytes,
			&i.Reclaimed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeCleanupItem = `-- name: CompleteCleanupItem :exec
WITH deleted AS (
    DELETE FROM cleanup_queue WHERE id = $1
    RETURNING backend_name, size_bytes
)
UPDATE backend_quotas bq
SET orphan_bytes = GREATEST(0, orphan_bytes - d.size_bytes)
FROM deleted d
WHERE bq.backend_name = d.backend_name
`

// Atomically removes a successfully-processed cleanup_queue row and
// decrements the backing backend's orphan_bytes by the row's size.
// Idempotent against re-claim retries: if the row was already deleted
// by a previous worker, the CTE is empty and orphan_bytes is not
// double-decremented. GREATEST(0, ...) clamps the counter so a stale
// size_bytes value cannot drive orphan_bytes negative.
func (q *Queries) CompleteCleanupItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeCleanupItem, id)
	return err
}

const countCleanupDLQ = `-- name: CountCleanupDLQ :one
SELECT COUNT(*) FROM cleanup_dlq
`

// Returns the current depth of the cleanup_dlq table for the dashboard
// and the cleanup_dlq_depth gauge.
func (q *Queries) CountCleanupDLQ(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCleanupDLQ)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingCleanups = `-- name: CountPendingCleanups :one
SELECT COUNT(*) FROM cleanup_queue WHERE attempts < 10
`

func (q *Queries) CountPendingCleanups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCleanups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCleanupItem = `-- name: DeleteCleanupItem :exec
DELETE FROM cleanup_queue WHERE id = $1
`

// Used inside the move-to-DLQ transaction; orphan_bytes is intentionally
// left untouched because the underlying backend object is still on disk.
// The cleanup worker's success path uses CompleteCleanupItem instead,
// which atomically deletes the row and decrements orphan_bytes.
func (q *Queries) DeleteCleanupItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCleanupItem, id)
	return err
}

const deleteCleanupQueueByBackend = `-- name: DeleteCleanupQueueByBackend :exec
DELETE FROM cleanup_queue WHERE backend_name = $1
`

func (q *Queries) DeleteCleanupQueueByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteCleanupQueueByBackend, backendName)
	return err
}

const deleteCleanupQueueByKey = `-- name: DeleteCleanupQueueByKey :execrows
DELETE FROM cleanup_queue
WHERE storage_key = $1 AND backend_name = $2
`

type DeleteCleanupQueueByKeyParams struct {
	StorageKey  string
	BackendName string
}

// Removes every cleanup_queue row matching the given (storage_key,
// backend_name) pair. Returns the number of rows deleted so the caller
// can confirm the sum-then-delete pair stayed consistent.
func (q *Queries) DeleteCleanupQueueByKey(ctx context.Context, arg DeleteCleanupQueueByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCleanupQueueByKey, arg.StorageKey, arg.BackendName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueCleanup = `-- name: EnqueueCleanup :exec

INSERT INTO cleanup_queue (backend_name, object_key, storage_key, reason, size_bytes)
VALUES ($1, $2, $3, $4, $5)
`

type EnqueueCleanupParams struct {
	BackendName string
	ObjectKey   string
	StorageKey  string
	Reason      string
	SizeBytes   int64
}

// -----------------------------------------------------------------------------
// Cleanup Queue Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for cleanup_queue and cleanup_dlq operations.
// Covers the enqueue + retry-state lifecycle, the move-to-DLQ flow that
// graduates exhausted rows, and the engine-side helpers core/ uses for the
// atomic stale-row sweep that keeps orphan_bytes in lockstep with row
// delete.
// -----------------------------------------------------------------------------
// storage_key is what the worker deletes; object_key rides along so an operator
// reading the queue still sees which object the orphan belongs to. They differ
// for every row written since per-write storage keys, and a row queued before
// them holds the same value in both.
func (q *Queries) EnqueueCleanup(ctx context.Context, arg EnqueueCleanupParams) error {
	_, err := q.db.Exec(ctx, enqueueCleanup,
		arg.BackendName,
		arg.ObjectKey,
		arg.StorageKey,
		arg.Reason,
		arg.SizeBytes,
	)
	return err
}

const getCleanupQueueRow = `-- name: GetCleanupQueueRow :one
SELECT id, backend_name, object_key, storage_key, reason, size_bytes,
       attempts, created_at, last_error
FROM cleanup_queue
WHERE id = $1
`

type GetCleanupQueueRowRow struct {
	ID          int64
	BackendName string
	ObjectKey   string
	StorageKey  string
	Reason      string
	SizeBytes   int64
	Attempts    int32
	CreatedAt   pgtype.Timestamptz
	LastError   *string
}

// Fetches a single cleanup_queue row by id along with the columns the
// DLQ insert needs (backend, key, reason, size, attempts, created_at,
// last_error). Used inside MoveCleanupToDLQ so the row contents survive
// the queue->DLQ move.
func (q *Queries) GetCleanupQueueRow(ctx context.Context, id int64) (GetCleanupQueueRowRow, error) {
	row := q.db.QueryRow(ctx, getCleanupQueueRow, id)
	var i GetCleanupQueueRowRow
	err := row.Scan(
		&i.ID,
		&i.BackendName,
		&i.ObjectKey,
		&i.StorageKey,
		&i.Reason,
		&i.SizeBytes,
		&i.Attempts,
		&i.CreatedAt,
		&i.LastError,
	)
	return i, err
}

const getPendingCleanups = `-- name: GetPendingCleanups :many
SELECT id, backend_name, object_key, storage_key, reason, attempts, size_bytes,
       claimed_at, claimed_by
FROM cleanup_queue
WHERE next_retry <= NOW() AND attempts < 10
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingCleanupsRow struct {
	ID          int64
	BackendName string
	ObjectKey   string
	StorageKey  string
	Reason      string
	Attempts    int32
	SizeBytes   int64
	ClaimedAt   pgtype.Timestamptz
	ClaimedBy   *string
}

// Read-only listing for the admin endpoint and operator visibility. The
// worker uses ClaimPendingCleanups instead, which also stamps the row.
// claimed_at and claimed_by are projected so the admin view can render
// which rows are currently held by a worker.
func (q *Queries) GetPendingCleanups(ctx context.Context, limit int32) ([]GetPendingCleanupsRow, error) {
	rows, err := q.db.Query(ctx, getPendingCleanups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingCleanupsRow{}
	for rows.Next() {
		var i GetPendingCleanupsRow
		if err := rows.Scan(
			&i.ID,
			&i.BackendName,
			&i.ObjectKey,
			&i.StorageKey,
			&i.Reason,
			&i.Attempts,
			&i.SizeBytes,
			&i.ClaimedAt,
			&i.ClaimedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPendingCleanup = `-- name: HasPendingCleanup :one
SELECT EXISTS (
    SELECT 1 FROM cleanup_queue q
     WHERE q.storage_key = $1 AND q.backend_name = $2
    UNION ALL
    SELECT 1 FROM cleanup_dlq d
     WHERE d.storage_key = $1 AND d.backend_name = $2
) AS pending
`

type HasPendingCleanupParams struct {
	StorageKey  string
	BackendName string
}

// Reports whether a delete for (object_key, backend_name) is still
// outstanding: either waiting in the retry queue or dead-lettered after
// exhausting its attempts. Both mean the bytes are still on the backend and
// the object is meant to be gone, which is what stops reconcile importing it
// back. Dead-lettered counts because retrying stopped, not because the delete
// was withdrawn.
func (q *Queries) HasPendingCleanup(ctx context.Context, arg HasPendingCleanupParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingCleanup, arg.StorageKey, arg.BackendName)
	var pending bool
	err := row.Scan(&pending)
	return pending, err
}

const insertCleanupDLQ = `-- name: InsertCleanupDLQ :exec
INSERT INTO cleanup_dlq (
    original_id, backend_name, object_key, storage_key, reason, size_bytes,
    attempts, first_enqueued_at, last_error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertCleanupDLQParams struct {
	OriginalID      int64
	BackendName     string
	ObjectKey       string
	StorageKey      string
	Reason          string
	SizeBytes       int64
	Attempts        int32
	FirstEnqueuedAt pgtype.Timestamptz
	LastError       *string
}

// Inserts an exhausted cleanup_queue row into the dead-letter table.
// The original_id retains the queue row's id for forensic correlation;
// first_enqueued_at carries the original created_at so the DLQ entry
// remembers how long the cleanup was outstanding.
func (q *Queries) InsertCleanupDLQ(ctx context.Context, arg InsertCleanupDLQParams) error {
	_, err := q.db.Exec(ctx, insertCleanupDLQ,
		arg.OriginalID,
		arg.BackendName,
		arg.ObjectKey,
		arg.StorageKey,
		arg.Reason,
		arg.SizeBytes,
		arg.Attempts,
		arg.FirstEnqueuedAt,
		arg.LastError,
	)
	return err
}

const listCleanupDLQ = `-- name: ListCleanupDLQ :many
SELECT backend_name, object_key, storage_key, reason, size_bytes,
       attempts, first_enqueued_at, moved_at, last_error
FROM cleanup_dlq
WHERE ($1::text = '' OR backend_name = $1)
ORDER BY moved_at DESC
LIMIT $2
`

type ListCleanupDLQParams struct {
	Backend  string
	RowLimit int32
}

type ListCleanupDLQRow struct {
	BackendName     string
	ObjectKey       string
	StorageKey      string
	Reason          string
	SizeBytes       int64
	Attempts        int32
	FirstEnqueuedAt pgtype.Timestamptz
	MovedAt         pgtype.Timestamptz
	LastError       *string
}

// Read-only listing of dead-lettered cleanups for the admin cleanup-dlq
// view. An empty backend argument returns every backend; otherwise the
// listing is scoped to one. Newest graduations first.
func (q *Queries) ListCleanupDLQ(ctx context.Context, arg ListCleanupDLQParams) ([]ListCleanupDLQRow, error) {
	rows, err := q.db.Query(ctx, listCleanupDLQ, arg.Backend, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCleanupDLQRow{}
	for rows.Next() {
		var i ListCleanupDLQRow
		if err := rows.Scan(
			&i.BackendName,
			&i.ObjectKey,
			&i.StorageKey,
			&i.Reason,
			&i.SizeBytes,
			&i.Attempts,
			&i.FirstEnqueuedAt,
			&i.MovedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueCleanupDLQ = `-- name: RequeueCleanupDLQ :execrows
WITH moved AS (
    DELETE FROM cleanup_dlq
    WHERE ($1::text = '' OR backend_name = $1)
    RETURNING backend_name, object_key, storage_key, reason, size_bytes
)
INSERT INTO cleanup_queue (backend_name, object_key, storage_key, reason, size_bytes)
SELECT backend_name, object_key, storage_key, reason, size_bytes FROM moved
`

// Atomically moves dead-lettered rows back into cleanup_queue so the
// cleanup worker retries them against a now-recovered backend. The
// writable CTE deletes the DLQ rows and re-inserts them in one
// statement; cleanup_queue defaults reset created_at/next_retry to NOW()
// and attempts to 0. orphan_bytes is untouched here - it was never
// decremented on the DLQ move, and the worker will debit it when the
// retried delete finally succeeds. An empty backend requeues every
// backend. Returns the number of rows requeued.
func (q *Queries) RequeueCleanupDLQ(ctx context.Context, backend string) (int64, error) {
	result, err := q.db.Exec(ctx, requeueCleanupDLQ, backend)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumCleanupQueueSizeByKey = `-- name: SumCleanupQueueSizeByKey :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes,
       COUNT(*)::bigint AS row_count
FROM cleanup_queue
WHERE storage_key = $1 AND backend_name = $2
`

type SumCleanupQueueSizeByKeyParams struct {
	StorageKey  string
	BackendName string
}

type SumCleanupQueueSizeByKeyRow struct {
	TotalBytes int64
	RowCount   int64
}

// Returns the sum of size_bytes for every cleanup_queue row matching the
// given (storage_key, backend_name) pair. Used by the reconciler-driven
// sweep so orphan_bytes can be decremented in step with the row delete.
//
// Matched on the path rather than the object, because the row being swept is a
// queued deletion of particular bytes and the reconcile that triggers it has
// established that those bytes are gone. Sweeping by object would also drop the
// queued deletions of the key's other writes, whose bytes are still there.
func (q *Queries) SumCleanupQueueSizeByKey(ctx context.Context, arg SumCleanupQueueSizeByKeyParams) (SumCleanupQueueSizeByKeyRow, error) {
	row := q.db.QueryRow(ctx, sumCleanupQueueSizeByKey, arg.StorageKey, arg.BackendName)
	var i SumCleanupQueueSizeByKeyRow
	err := row.Scan(&i.TotalBytes, &i.RowCount)
	return i, err
}

const updateCleanupRetry = `-- name: UpdateCleanupRetry :exec
UPDATE cleanup_queue
SET attempts = attempts + 1,
    next_retry = NOW() + $1::interval,
    last_error = $2,
    claimed_at = NULL,
    claimed_by = NULL
WHERE id = $3
`

type UpdateCleanupRetryParams struct {
	Backoff   pgtype.Interval
	LastError *string
	ID        int64
}

// Schedules a retry by advancing next_retry, recording the error, and
// clearing the claim so the row is immediately re-eligible for the next
// worker tick (the previous claim is what gated this retry from running
// twice within the grace window).
func (q *Queries) UpdateCleanupRetry(ctx context.Context, arg UpdateCleanupRetryParams) error {
	_, err := q.db.Exec(ctx, updateCleanupRetry, arg.Backoff, arg.LastError, arg.ID)
	return err
}
