// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BackendQuota struct {
	BackendName string
	BytesLimit  int64
	UpdatedAt   pgtype.Timestamptz
	OrphanBytes int64
}

type BackendQuotaStripe struct {
	BackendName string
	StripeID    int16
	BytesUsed   int64
}

type BackendRequestUsage struct {
	BackendName string
	Period      string
	Pool        string
	Requests    int64
	UpdatedAt   pgtype.Timestamptz
}

type BackendUsage struct {
	BackendName  string
	Period       string
	ApiRequests  int64
	EgressBytes  int64
	IngressBytes int64
	UpdatedAt    pgtype.Timestamptz
}

type Bucket struct {
	Name                string
	MaxMultipartUploads int32
	Cors                []byte
	CreatedAt           pgtype.Timestamptz
}

type CleanupDlq struct {
	ID              int64
	OriginalID      int64
	BackendName     string
	ObjectKey       string
	Reason          string
	SizeBytes       int64
	Attempts        int32
	FirstEnqueuedAt pgtype.Timestamptz
	MovedAt         pgtype.Timestamptz
	LastError       *string
	StorageKey      string
}

type CleanupQueue struct {
	ID          int64
	BackendName string
	ObjectKey   string
	Reason      string
	CreatedAt   pgtype.Timestamptz
	NextRetry   pgtype.Timestamptz
	Attempts    int32
	LastError   *string
	SizeBytes   int64
	ClaimedAt   pgtype.Timestamptz
	ClaimedBy   *string
	StorageKey  string
}

type Credential struct {
	AccessKeyID string
	UserID      string
	Secret      string
	Label       *string
	Disabled    bool
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
}

type Grant struct {
	UserID       string
	ResourceName string
	CreatedAt    pgtype.Timestamptz
	Permissions  string
	ResourceKind string
}

type MultipartPart struct {
	UploadID      string
	PartNumber    int32
	Etag          string
	SizeBytes     int64
	CreatedAt     pgtype.Timestamptz
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	PlaintextEtag *string
}

type MultipartUpload struct {
	UploadID      string
	ObjectKey     string
	BackendName   string
	ContentType   *string
	CreatedAt     pgtype.Timestamptz
	Metadata      []byte
	EncryptionKey []byte
	KeyID         *string
	Tagging       *string
}

type NotificationOutbox struct {
	ID          int64
	EventType   string
	Payload     []byte
	EndpointUrl string
	CreatedAt   pgtype.Timestamptz
	NextRetry   pgtype.Timestamptz
	Attempts    int32
	LastError   *string
}

type ObjectLocation struct {
	ObjectKey                string
	BackendName              string
	SizeBytes                int64
	CreatedAt                pgtype.Timestamptz
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	Managed                  bool
	LastScrubbedAt           pgtype.Timestamptz
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	CompressionProbeSize     *int64
	CompressionProbeLevel    *string
	Etag                     *string
	ContentType              *string
	UserMetadata             []byte
	StorageKey               string
}

type ObjectTag struct {
	ObjectKey string
	TagKey    string
	TagValue  string
}

type PendingObject struct {
	IntentID                 string
	ObjectKey                string
	BackendName              string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	CreatedAt                pgtype.Timestamptz
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	Etag                     *string
	ContentType              *string
	UserMetadata             []byte
	Role                     string
	StorageKey               string
}

type User struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}
