// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backendObjectStats = `-- name: BackendObjectStats :one
SELECT COUNT(*) AS object_count, COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes
FROM object_locations
WHERE backend_name = $1
`

type BackendObjectStatsRow struct {
	ObjectCount int64
	TotalBytes  int64
}

func (q *Queries) BackendObjectStats(ctx context.Context, backendName string) (BackendObjectStatsRow, error) {
	row := q.db.QueryRow(ctx, backendObjectStats, backendName)
	var i BackendObjectStatsRow
	err := row.Scan(&i.ObjectCount, &i.TotalBytes)
	return i, err
}

const checkObjectExistsOnBackend = `-- name: CheckObjectExistsOnBackend :one
SELECT EXISTS(
    SELECT 1 FROM object_locations
    WHERE object_key = $1 AND backend_name = $2
) AS exists
`

type CheckObjectExistsOnBackendParams struct {
	ObjectKey   string
	BackendName string
}

func (q *Queries) CheckObjectExistsOnBackend(ctx context.Context, arg CheckObjectExistsOnBackendParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkObjectExistsOnBackend, arg.ObjectKey, arg.BackendName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const compressionStats = `-- name: CompressionStats :many
SELECT backend_name,
       count(*) AS objects,
       COALESCE(SUM(logical_size), 0)::bigint AS logical_bytes,
       COALESCE(SUM(size_bytes), 0)::bigint AS stored_bytes
FROM object_locations
WHERE compression_algorithm IS NOT NULL
GROUP BY backend_name
`

type CompressionStatsRow struct {
	BackendName  string
	Objects      int64
	LogicalBytes int64
	StoredBytes  int64
}

// What compression is worth, per backend. Only encoded copies are counted:
// including the verbatim ones would report a ratio no encoder produced. The
// saving is logical - stored, left to the caller so it cannot disagree with the
// two figures it comes from.
func (q *Queries) CompressionStats(ctx context.Context) ([]CompressionStatsRow, error) {
	rows, err := q.db.Query(ctx, compressionStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompressionStatsRow{}
	for rows.Next() {
		var i CompressionStatsRow
		if err := rows.Scan(
			&i.BackendName,
			&i.Objects,
			&i.LogicalBytes,
			&i.StoredBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const copyExistsAtPath = `-- name: CopyExistsAtPath :one
SELECT EXISTS(
    SELECT 1 FROM object_locations
    WHERE backend_name = $1 AND storage_key = $2
) AS exists
`

type CopyExistsAtPathParams struct {
	BackendName string
	StorageKey  string
}

// Whether the backend already has a copy recorded at this path, whatever
// object it belongs to. Import asks before adopting bytes it found, because
// the object key it would record them under is the path itself, which says
// nothing about the row an orchestrator-written path already has under the
// real object's key.
func (q *Queries) CopyExistsAtPath(ctx context.Context, arg CopyExistsAtPathParams) (bool, error) {
	row := q.db.QueryRow(ctx, copyExistsAtPath, arg.BackendName, arg.StorageKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countObjectsByPrefix = `-- name: CountObjectsByPrefix :one
SELECT count(DISTINCT object_key)
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
`

// Distinct keys, not copies: an object replicated three times is one object to
// an operator asking whether a bucket is empty. The prefix is escaped the same
// way ListObjectsByPrefix escapes it, so a bucket whose name contains a LIKE
// metacharacter counts its own keys rather than a wider set.
func (q *Queries) CountObjectsByPrefix(ctx context.Context, prefix string) (int64, error) {
	row := q.db.QueryRow(ctx, countObjectsByPrefix, prefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScrubCandidatesOnBackends = `-- name: CountScrubCandidatesOnBackends :one
SELECT count(*)
FROM object_locations
WHERE content_hash IS NOT NULL AND managed
  AND backend_name = ANY($1::text[])
`

// Copies eligible for scrubbing that live on the named backends. Used to report
// how much of the queue a cycle declined to read, which a sampled count of the
// batch cannot show.
func (q *Queries) CountScrubCandidatesOnBackends(ctx context.Context, backendNames []string) (int64, error) {
	row := q.db.QueryRow(ctx, countScrubCandidatesOnBackends, backendNames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnencryptedLocations = `-- name: CountUnencryptedLocations :one
SELECT count(*) FROM object_locations WHERE encrypted = FALSE
`

// Copies still stored as plaintext. Uses the same predicate as
// ListUnencryptedLocations, so the figure is exactly what encrypt-existing
// would process rather than a differently-scoped count that happens to be near
// it.
func (q *Queries) CountUnencryptedLocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnencryptedLocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteObjectCopies = `-- name: DeleteObjectCopies :exec
DELETE FROM object_locations
WHERE object_key = $1
`

func (q *Queries) DeleteObjectCopies(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, deleteObjectCopies, objectKey)
	return err
}

const deleteObjectFromBackend = `-- name: DeleteObjectFromBackend :exec
DELETE FROM object_locations
WHERE object_key = $1 AND backend_name = $2
`

type DeleteObjectFromBackendParams struct {
	ObjectKey   string
	BackendName string
}

func (q *Queries) DeleteObjectFromBackend(ctx context.Context, arg DeleteObjectFromBackendParams) error {
	_, err := q.db.Exec(ctx, deleteObjectFromBackend, arg.ObjectKey, arg.BackendName)
	return err
}

const deleteObjectLocationsByBackend = `-- name: DeleteObjectLocationsByBackend :exec
DELETE FROM object_locations WHERE backend_name = $1
`

func (q *Queries) DeleteObjectLocationsByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteObjectLocationsByBackend, backendName)
	return err
}

const deleteObjectsByKeys = `-- name: DeleteObjectsByKeys :exec
DELETE FROM object_locations
WHERE object_key = ANY($1::text[])
`

// Deletes every row whose object_key is in the supplied list. Caller
// must have already locked the rows via GetCopiesForKeysForUpdate.
func (q *Queries) DeleteObjectsByKeys(ctx context.Context, objectKeys []string) error {
	_, err := q.db.Exec(ctx, deleteObjectsByKeys, objectKeys)
	return err
}

const getAllObjectLocations = `-- name: GetAllObjectLocations :many
SELECT object_key, backend_name, storage_key, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_format_version, logical_size, etag, content_type, user_metadata, created_at, last_scrubbed_at
FROM object_locations
WHERE object_key = $1
ORDER BY created_at ASC
`

type GetAllObjectLocationsRow struct {
	ObjectKey                string
	BackendName              string
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	Etag                     *string
	ContentType              *string
	UserMetadata             []byte
	CreatedAt                pgtype.Timestamptz
	LastScrubbedAt           pgtype.Timestamptz
}

func (q *Queries) GetAllObjectLocations(ctx context.Context, objectKey string) ([]GetAllObjectLocationsRow, error) {
	rows, err := q.db.Query(ctx, getAllObjectLocations, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllObjectLocationsRow{}
	for rows.Next() {
		var i GetAllObjectLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionFormatVersion,
			&i.LogicalSize,
			&i.Etag,
			&i.ContentType,
			&i.UserMetadata,
			&i.CreatedAt,
			&i.LastScrubbedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCopiesForKeysForUpdate = `-- name: GetCopiesForKeysForUpdate :many
SELECT object_key, backend_name, storage_key, size_bytes
FROM object_locations
WHERE object_key = ANY($1::text[])
FOR UPDATE
`

type GetCopiesForKeysForUpdateRow struct {
	ObjectKey   string
	BackendName string
	StorageKey  string
	SizeBytes   int64
}

// Returns (object_key, backend_name, size_bytes) for every row matching
// a key in the supplied list, locked FOR UPDATE so the same transaction
// can delete the rows and decrement the corresponding backend quotas
// atomically. Used by the batch-delete path so an N-key request is one
// transaction instead of N.
func (q *Queries) GetCopiesForKeysForUpdate(ctx context.Context, objectKeys []string) ([]GetCopiesForKeysForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getCopiesForKeysForUpdate, objectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCopiesForKeysForUpdateRow{}
	for rows.Next() {
		var i GetCopiesForKeysForUpdateRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectoryStats = `-- name: GetDirectoryStats :many
SELECT
    (CASE WHEN position('/' IN substr(object_key, $1::int)) > 0
         THEN substr(object_key, $1::int,
              position('/' IN substr(object_key, $1::int)))
         ELSE substr(object_key, $1::int)
    END)::text AS name,
    (CASE WHEN position('/' IN substr(object_key, $1::int)) > 0
         THEN true ELSE false
    END)::boolean AS is_dir,
    COUNT(DISTINCT object_key) AS file_count,
    COALESCE(SUM(size_bytes), 0)::bigint AS total_size
FROM object_locations
WHERE object_key LIKE $2::text || '%' ESCAPE '\'
  AND length(object_key) >= $1::int
GROUP BY name, is_dir
ORDER BY is_dir DESC, name ASC
`

type GetDirectoryStatsParams struct {
	NameStart int32
	Prefix    string
}

type GetDirectoryStatsRow struct {
	Name      string
	IsDir     bool
	FileCount int64
	TotalSize int64
}

// Aggregate count and size for immediate children of a directory prefix.
// Directories (containing a '/') and files are distinguished by is_dir.
// file_count counts distinct object_keys (logical files); total_size sums
// every replica row in object_locations so directory totals reflect real
// physical storage consumption, matching the Storage Summary semantics.
// @prefix is LIKE-escaped for the WHERE match; @name_start is the 1-based
// character position where the child name begins (len(unescaped prefix) + 1),
// so escaped wildcards (e.g. '\_') don't shift the substring cut point.
func (q *Queries) GetDirectoryStats(ctx context.Context, arg GetDirectoryStatsParams) ([]GetDirectoryStatsRow, error) {
	rows, err := q.db.Query(ctx, getDirectoryStats, arg.NameStart, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDirectoryStatsRow{}
	for rows.Next() {
		var i GetDirectoryStatsRow
		if err := rows.Scan(
			&i.Name,
			&i.IsDir,
			&i.FileCount,
			&i.TotalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingCopiesForUpdate = `-- name: GetExistingCopiesForUpdate :many
SELECT backend_name, storage_key, size_bytes, created_at, encrypted,
       (encryption_key IS NOT NULL AND length(encryption_key) > 0) AS has_dek
FROM object_locations
WHERE object_key = $1
FOR UPDATE
`

type GetExistingCopiesForUpdateRow struct {
	BackendName string
	StorageKey  string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
	Encrypted   bool
	HasDek      *bool
}

// storage_key comes along because the caller that deletes these rows is also
// the caller that deletes their bytes, and after per-write storage keys the
// path is no longer derivable from the object key.
func (q *Queries) GetExistingCopiesForUpdate(ctx context.Context, objectKey string) ([]GetExistingCopiesForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getExistingCopiesForUpdate, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExistingCopiesForUpdateRow{}
	for rows.Next() {
		var i GetExistingCopiesForUpdateRow
		if err := rows.Scan(
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.Encrypted,
			&i.HasDek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeastRecentlyScrubbedObjects = `-- name: GetLeastRecentlyScrubbedObjects :many
SELECT object_key, backend_name, storage_key, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_format_version, logical_size, created_at, last_scrubbed_at
FROM object_locations
WHERE content_hash IS NOT NULL AND managed
  AND backend_name = ANY($1::text[])
ORDER BY COALESCE(last_scrubbed_at, created_at) ASC, object_key ASC
LIMIT $2
`

type GetLeastRecentlyScrubbedObjectsParams struct {
	BackendNames []string
	RowLimit     int32
}

type GetLeastRecentlyScrubbedObjectsRow struct {
	ObjectKey                string
	BackendName              string
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	CreatedAt                pgtype.Timestamptz
	LastScrubbedAt           pgtype.Timestamptz
}

// Return the copies least recently touched, by verification or by writing.
//
// Falling back to created_at is what keeps the sweep alive on a busy fleet: a
// copy written moments ago sorts to the back rather than jumping the queue, so
// a write rate above the scrub rate cannot starve older data. It also puts the
// effort where rot actually accumulates, since churn is deleted long before it
// degrades while the copies that persist for months are the ones at risk.
//
// backend_names restricts the batch to copies the scrubber can afford to read.
// Filtering here rather than after selection is what keeps a sweep useful when
// a backend is over its usage limit: a copy the scrubber would decline never
// occupies a slot, so it is neither stamped as examined nor left at the head of
// the queue to be re-selected every cycle.
func (q *Queries) GetLeastRecentlyScrubbedObjects(ctx context.Context, arg GetLeastRecentlyScrubbedObjectsParams) ([]GetLeastRecentlyScrubbedObjectsRow, error) {
	rows, err := q.db.Query(ctx, getLeastRecentlyScrubbedObjects, arg.BackendNames, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeastRecentlyScrubbedObjectsRow{}
	for rows.Next() {
		var i GetLeastRecentlyScrubbedObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionFormatVersion,
			&i.LogicalSize,
			&i.CreatedAt,
			&i.LastScrubbedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectBackendsForKeys = `-- name: GetObjectBackendsForKeys :many
SELECT object_key, backend_name
FROM object_locations
WHERE object_key = ANY($1::text[])
`

type GetObjectBackendsForKeysRow struct {
	ObjectKey   string
	BackendName string
}

// Returns (object_key, backend_name) for every object_locations row whose
// object_key is in the supplied list. Used by the rebalancer planner to
// determine which backends already hold a copy of each candidate key in a
// batch, replacing the per-key GetAllObjectLocations N+1 pattern.
func (q *Queries) GetObjectBackendsForKeys(ctx context.Context, objectKeys []string) ([]GetObjectBackendsForKeysRow, error) {
	rows, err := q.db.Query(ctx, getObjectBackendsForKeys, objectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectBackendsForKeysRow{}
	for rows.Next() {
		var i GetObjectBackendsForKeysRow
		if err := rows.Scan(&i.ObjectKey, &i.BackendName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectsWithoutHash = `-- name: GetObjectsWithoutHash :many
SELECT object_key, backend_name, storage_key, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_format_version, logical_size, created_at
FROM object_locations
WHERE content_hash IS NULL AND managed
  AND ($1::text = '' OR backend_name = $1::text)
ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type GetObjectsWithoutHashParams struct {
	BackendFilter string
	RowOffset     int32
	RowLimit      int32
}

type GetObjectsWithoutHashRow struct {
	ObjectKey                string
	BackendName              string
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	CreatedAt                pgtype.Timestamptz
}

// Return object locations that have no content hash, for backfill. Hashing
// reads the whole body, so unmanaged rows are left alone rather than spending
// egress on data the orchestrator does not manage.
func (q *Queries) GetObjectsWithoutHash(ctx context.Context, arg GetObjectsWithoutHashParams) ([]GetObjectsWithoutHashRow, error) {
	rows, err := q.db.Query(ctx, getObjectsWithoutHash, arg.BackendFilter, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectsWithoutHashRow{}
	for rows.Next() {
		var i GetObjectsWithoutHashRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.ContentHash,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionFormatVersion,
			&i.LogicalSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertObjectLocation = `-- name: InsertObjectLocation :exec
INSERT INTO object_locations (object_key, backend_name, storage_key, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_format_version, logical_size, etag, content_type, user_metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, NOW())
`

type InsertObjectLocationParams struct {
	ObjectKey                string
	BackendName              string
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	Etag                     *string
	ContentType              *string
	UserMetadata             []byte
}

func (q *Queries) InsertObjectLocation(ctx context.Context, arg InsertObjectLocationParams) error {
	_, err := q.db.Exec(ctx, insertObjectLocation,
		arg.ObjectKey,
		arg.BackendName,
		arg.StorageKey,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.ContentHash,
		arg.CompressionAlgorithm,
		arg.CompressionLevel,
		arg.CompressionFormatVersion,
		arg.LogicalSize,
		arg.Etag,
		arg.ContentType,
		arg.UserMetadata,
	)
	return err
}

const insertObjectLocationIfNotExists = `-- name: InsertObjectLocationIfNotExists :one
INSERT INTO object_locations (object_key, backend_name, storage_key, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash, compression_algorithm, compression_level, compression_format_version, logical_size, etag, content_type, user_metadata, managed, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (object_key, backend_name) DO NOTHING
RETURNING true AS inserted
`

type InsertObjectLocationIfNotExistsParams struct {
	ObjectKey                string
	BackendName              string
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	Etag                     *string
	ContentType              *string
	UserMetadata             []byte
	Managed                  bool
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) InsertObjectLocationIfNotExists(ctx context.Context, arg InsertObjectLocationIfNotExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, insertObjectLocationIfNotExists,
		arg.ObjectKey,
		arg.BackendName,
		arg.StorageKey,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.ContentHash,
		arg.CompressionAlgorithm,
		arg.CompressionLevel,
		arg.CompressionFormatVersion,
		arg.LogicalSize,
		arg.Etag,
		arg.ContentType,
		arg.UserMetadata,
		arg.Managed,
		arg.CreatedAt,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const integrityCoverage = `-- name: IntegrityCoverage :one
SELECT
    COALESCE(EXTRACT(EPOCH FROM (NOW() - MIN(COALESCE(last_scrubbed_at, created_at))
        FILTER (WHERE backend_name = ANY($1::text[])))), 0)::bigint AS age_seconds,
    COUNT(*) FILTER (WHERE last_scrubbed_at IS NULL
        AND backend_name = ANY($1::text[]))::bigint AS never_verified,
    COUNT(*) FILTER (WHERE NOT (backend_name = ANY($1::text[])))::bigint AS deferred
FROM object_locations
WHERE content_hash IS NOT NULL AND managed
`

type IntegrityCoverageRow struct {
	AgeSeconds    int64
	NeverVerified int64
	Deferred      int64
}

// How far behind verification is, split by whether the sweep can reach the copy
// at all. Reachable is the same backend set the scrub queue draws from.
//
// The age and the never-verified count cover reachable copies only. A copy the
// sweep is not allowed to read can never be stamped, so counting it pins
// MIN(COALESCE(last_scrubbed_at, created_at)) to a fixed timestamp and the age
// then tracks wall clock rather than the backlog: it climbs by a day every day
// no matter how much the sweep verifies, and no amount of scrubbing lowers it.
//
// Deferred counts the rest rather than discarding them, so a fleet holding most
// of its copies on a backend over its usage limit cannot report as healthy.
//
// The age falls back to created_at exactly as the queue ordering does, so a
// never-verified copy is measured from when it was written. Taking MIN over
// last_scrubbed_at alone skips those rows entirely, which reports a fleet that
// has never been scrubbed as an age of zero.
func (q *Queries) IntegrityCoverage(ctx context.Context, reachableBackends []string) (IntegrityCoverageRow, error) {
	row := q.db.QueryRow(ctx, integrityCoverage, reachableBackends)
	var i IntegrityCoverageRow
	err := row.Scan(&i.AgeSeconds, &i.NeverVerified, &i.Deferred)
	return i, err
}

const listAllEncryptedLocations = `-- name: ListAllEncryptedLocations :many
SELECT object_key, backend_name, storage_key, size_bytes, encryption_key, key_id, plaintext_size, etag
FROM object_locations
WHERE encrypted = TRUE
  AND ($1::text = '' OR backend_name = $1::text)
  AND (object_key, backend_name) > ($2::text, $3::text)
ORDER BY object_key, backend_name
LIMIT $4
`

type ListAllEncryptedLocationsParams struct {
	BackendFilter string
	AfterKey      string
	AfterBackend  string
	RowLimit      int32
}

type ListAllEncryptedLocationsRow struct {
	ObjectKey     string
	BackendName   string
	StorageKey    string
	SizeBytes     int64
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	Etag          *string
}

// Cursor-paged for the same reason as ListUnencryptedLocations: decrypting a
// copy removes it from this set mid-walk.
func (q *Queries) ListAllEncryptedLocations(ctx context.Context, arg ListAllEncryptedLocationsParams) ([]ListAllEncryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listAllEncryptedLocations,
		arg.BackendFilter,
		arg.AfterKey,
		arg.AfterBackend,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEncryptedLocationsRow{}
	for rows.Next() {
		var i ListAllEncryptedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompressedLocations = `-- name: ListCompressedLocations :many
SELECT object_key, backend_name, storage_key, size_bytes, encrypted, encryption_key, key_id,
       plaintext_size, compression_algorithm, compression_level,
       compression_format_version, logical_size, etag
FROM object_locations
WHERE compression_algorithm IS NOT NULL
  AND ($1::text = '' OR backend_name = $1::text)
  AND (object_key, backend_name) > ($2::text, $3::text)
ORDER BY object_key, backend_name
LIMIT $4
`

type ListCompressedLocationsParams struct {
	BackendFilter string
	AfterKey      string
	AfterBackend  string
	RowLimit      int32
}

type ListCompressedLocationsRow struct {
	ObjectKey                string
	BackendName              string
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	Etag                     *string
}

// The complement of ListUncompressedLocations, which is what
// decompress-existing rewrites. Cursor-paged for the same reason, and the case
// that makes it matter most: every object this pass succeeds on leaves the
// predicate, so an offset walk would skip whole pages and stop early.
func (q *Queries) ListCompressedLocations(ctx context.Context, arg ListCompressedLocationsParams) ([]ListCompressedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listCompressedLocations,
		arg.BackendFilter,
		arg.AfterKey,
		arg.AfterBackend,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompressedLocationsRow{}
	for rows.Next() {
		var i ListCompressedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionFormatVersion,
			&i.LogicalSize,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChildren = `-- name: ListDirectChildren :many
SELECT
    object_key,
    ARRAY_AGG(backend_name ORDER BY backend_name)::text[] AS backend_names,
    MAX(size_bytes)::bigint AS size_bytes,
    MIN(created_at)::timestamptz AS created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND position('/' IN substring(object_key FROM length($1::text) + 1)) = 0
  AND length(object_key) > length($1::text)
  AND object_key > $2
GROUP BY object_key
ORDER BY object_key
LIMIT $3
`

type ListDirectChildrenParams struct {
	Prefix     string
	StartAfter string
	MaxKeys    int32
}

type ListDirectChildrenRow struct {
	ObjectKey    string
	BackendNames []string
	SizeBytes    int64
	CreatedAt    pgtype.Timestamptz
}

// Return per-file detail for non-directory children under a prefix, with pagination.
// Aggregates every replica into a sorted backend_names array per object_key so
// the file row reflects all backends a file lives on, not just one.
func (q *Queries) ListDirectChildren(ctx context.Context, arg ListDirectChildrenParams) ([]ListDirectChildrenRow, error) {
	rows, err := q.db.Query(ctx, listDirectChildren, arg.Prefix, arg.StartAfter, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectChildrenRow{}
	for rows.Next() {
		var i ListDirectChildrenRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendNames,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptedLocations = `-- name: ListEncryptedLocations :many
SELECT object_key, backend_name, encryption_key, key_id
FROM object_locations
WHERE encrypted = TRUE AND key_id = $1
ORDER BY object_key, backend_name
LIMIT $2 OFFSET $3
`

type ListEncryptedLocationsParams struct {
	KeyID  *string
	Limit  int32
	Offset int32
}

type ListEncryptedLocationsRow struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
}

func (q *Queries) ListEncryptedLocations(ctx context.Context, arg ListEncryptedLocationsParams) ([]ListEncryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listEncryptedLocations, arg.KeyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEncryptedLocationsRow{}
	for rows.Next() {
		var i ListEncryptedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.EncryptionKey,
			&i.KeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredObjects = `-- name: ListExpiredObjects :many
SELECT DISTINCT ON (ol.object_key COLLATE "C") ol.object_key, ol.backend_name, ol.storage_key, ol.size_bytes, ol.created_at
FROM object_locations ol
WHERE ol.object_key LIKE $1::text || '%' ESCAPE '\'
  AND ol.created_at < $2
  AND (
    $3::int = 0
    OR (
      SELECT COUNT(*)
      FROM object_tags t
      JOIN jsonb_each_text($4::jsonb) AS f(k, v)
        ON t.tag_key = f.k AND t.tag_value = f.v
      WHERE t.object_key = ol.object_key
    ) = $3::int
  )
ORDER BY ol.object_key COLLATE "C", ol.created_at ASC
LIMIT $5
`

type ListExpiredObjectsParams struct {
	Prefix   string
	Cutoff   pgtype.Timestamptz
	TagCount int32
	Tags     []byte
	MaxKeys  int32
}

type ListExpiredObjectsRow struct {
	ObjectKey   string
	BackendName string
	StorageKey  string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

// Collated for the same reason as ListObjectsByPrefix. The expiry worker does
// not depend on the order, but a batch that differs by engine is one more thing
// an operator has to hold in their head when a run is reproduced elsewhere.
//
// The tag filter is a correlated subquery rather than a join: a join against
// object_tags multiplies the row per matching tag, and this query's DISTINCT ON
// and its matching ORDER BY are what reduce an object's replicas to one row.
// Counting in a subquery leaves both untouched.
//
// Requiring the count to equal tag_count is what makes several tags an AND.
// The primary key allows one row per (object_key, tag_key), so a count equal to
// the number of pairs asked for means every one of them matched.
func (q *Queries) ListExpiredObjects(ctx context.Context, arg ListExpiredObjectsParams) ([]ListExpiredObjectsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredObjects,
		arg.Prefix,
		arg.Cutoff,
		arg.TagCount,
		arg.Tags,
		arg.MaxKeys,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredObjectsRow{}
	for rows.Next() {
		var i ListExpiredObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByBackend = `-- name: ListObjectsByBackend :many
SELECT object_key, backend_name, storage_key, size_bytes, created_at
FROM object_locations
WHERE backend_name = $1 AND managed
ORDER BY size_bytes ASC
LIMIT $2
`

type ListObjectsByBackendParams struct {
	BackendName string
	Limit       int32
}

type ListObjectsByBackendRow struct {
	ObjectKey   string
	BackendName string
	StorageKey  string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

// ListObjectsByBackend backs the rebalance, placement and drain candidate
// scans, so it returns managed rows only. Objects outside every configured
// bucket prefix are tracked for accounting but are not the orchestrator's to
// move.
func (q *Queries) ListObjectsByBackend(ctx context.Context, arg ListObjectsByBackendParams) ([]ListObjectsByBackendRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByBackend, arg.BackendName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByBackendRow{}
	for rows.Next() {
		var i ListObjectsByBackendRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByBackendKeyAsc = `-- name: ListObjectsByBackendKeyAsc :many
SELECT object_key, backend_name, storage_key, size_bytes, created_at
FROM object_locations
WHERE backend_name = $1 AND storage_key COLLATE "C" > $2
ORDER BY storage_key COLLATE "C" ASC
LIMIT $3
`

type ListObjectsByBackendKeyAscParams struct {
	BackendName string
	StorageKey  string
	Limit       int32
}

type ListObjectsByBackendKeyAscRow struct {
	ObjectKey   string
	BackendName string
	StorageKey  string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

// ListObjectsByBackendKeyAsc returns rows for a backend in ascending
// storage_key order, starting strictly after the supplied cursor. Used by
// ReconcileBackend to drive a bounded-memory sorted-merge join against an S3
// ListObjects walk. Pass ” as the cursor on the first call.
//
// storage_key rather than object_key because that is what the other side of the
// merge returns: a backend lists the paths it holds, and after per-write
// storage keys a path is no longer the object's key. Walking by object_key
// would pair every row against the wrong listing entry, which the merge reports
// as one import and one delete per object, forever.
//
// COLLATE "C" is required: the merge join compares keys in byte order (Go string
// comparison) against S3 ListObjectsV2, which is UTF-8 byte ordered. Without it,
// a locale-collated column orders the cursor differently, the merge mis-pairs
// keys, and reconcile oscillates (false imports/removes that never converge).
// The cursor predicate and ORDER BY must use the same collation.
func (q *Queries) ListObjectsByBackendKeyAsc(ctx context.Context, arg ListObjectsByBackendKeyAscParams) ([]ListObjectsByBackendKeyAscRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByBackendKeyAsc, arg.BackendName, arg.StorageKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByBackendKeyAscRow{}
	for rows.Next() {
		var i ListObjectsByBackendKeyAscRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByPrefix = `-- name: ListObjectsByPrefix :many
SELECT DISTINCT ON (object_key COLLATE "C") object_key, backend_name, storage_key, size_bytes, etag, created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND object_key COLLATE "C" > $2
ORDER BY object_key COLLATE "C", created_at ASC
LIMIT $3
`

type ListObjectsByPrefixParams struct {
	Prefix     string
	StartAfter string
	MaxKeys    int32
}

type ListObjectsByPrefixRow struct {
	ObjectKey   string
	BackendName string
	StorageKey  string
	SizeBytes   int64
	Etag        *string
	CreatedAt   pgtype.Timestamptz
}

// COLLATE "C" is required: S3 ListObjectsV2 returns keys in UTF-8 byte order,
// and object_key is plain TEXT so it would otherwise sort under the database's
// LC_COLLATE. The cursor predicate carries the same collation as the ORDER BY -
// splitting them would page a byte-ordered scan with a locale-ordered cursor and
// skip or repeat keys. DISTINCT ON must carry it too, or Postgres rejects the
// query for not matching the leading ORDER BY expression.
func (q *Queries) ListObjectsByPrefix(ctx context.Context, arg ListObjectsByPrefixParams) ([]ListObjectsByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByPrefix, arg.Prefix, arg.StartAfter, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByPrefixRow{}
	for rows.Next() {
		var i ListObjectsByPrefixRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Etag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsDelimited = `-- name: ListObjectsDelimited :many
WITH RECURSIVE walk(k) AS (
    (SELECT object_key
       FROM object_locations
      WHERE object_key LIKE $4::text || '%' ESCAPE '\'
        AND object_key COLLATE "C" > $5::text
      ORDER BY object_key COLLATE "C"
      LIMIT 1)
    UNION ALL
    SELECT (
        SELECT object_key
          FROM object_locations
         WHERE object_key LIKE $4::text || '%' ESCAPE '\'
           AND object_key COLLATE "C" > CASE
            WHEN position($2::text IN substr(walk.k, length($1::text) + 1)) > 0 THEN
                substr(walk.k, 1, length($1::text) + position($2::text IN substr(walk.k, length($1::text) + 1)) + length($2::text) - 2)
                || chr(ascii(substr(walk.k, length($1::text) + position($2::text IN substr(walk.k, length($1::text) + 1)) + length($2::text) - 1, 1)) + 1)
            ELSE walk.k
           END
         ORDER BY object_key COLLATE "C"
         LIMIT 1
    )
    FROM walk WHERE walk.k IS NOT NULL
)
SELECT
    w.k::text AS object_key,
    (position($2::text IN substr(w.k, length($1::text) + 1)) > 0)::boolean AS is_prefix,
    (CASE WHEN position($2::text IN substr(w.k, length($1::text) + 1)) > 0
        THEN substr(w.k, 1, length($1::text) + position($2::text IN substr(w.k, length($1::text) + 1)) + length($2::text) - 1)
        ELSE '' END)::text AS common_prefix,
    (CASE WHEN position($2::text IN substr(w.k, length($1::text) + 1)) > 0 THEN
            substr(w.k, 1, length($1::text) + position($2::text IN substr(w.k, length($1::text) + 1)) + length($2::text) - 2)
            || chr(ascii(substr(w.k, length($1::text) + position($2::text IN substr(w.k, length($1::text) + 1)) + length($2::text) - 1, 1)) + 1)
        ELSE w.k END)::text AS skip_bound,
    COALESCE(leaf.backend_name, '')::text AS backend_name,
    COALESCE(leaf.size_bytes, 0)::bigint AS size_bytes,
    COALESCE(leaf.etag, '')::text AS etag,
    COALESCE(leaf.created_at, to_timestamp(0)) AS created_at
FROM walk w
LEFT JOIN LATERAL (
    SELECT backend_name, size_bytes, etag, created_at
      FROM object_locations o2
     WHERE o2.object_key = w.k
       AND position($2::text IN substr(w.k, length($1::text) + 1)) = 0
     ORDER BY created_at ASC
     LIMIT 1
) leaf ON true
WHERE w.k IS NOT NULL
ORDER BY w.k COLLATE "C"
LIMIT $3::int
`

type ListObjectsDelimitedParams struct {
	Prefix     string
	Delim      string
	Lim        int32
	Escprefix  string
	StartAfter string
}

type ListObjectsDelimitedRow struct {
	ObjectKey    string
	IsPrefix     bool
	CommonPrefix string
	SkipBound    string
	BackendName  string
	SizeBytes    int64
	Etag         string
	CreatedAt    pgtype.Timestamptz
}

// Every projected column is forced non-null (empty string / 0 / epoch) because
// the built-in sqlc analyzer cannot infer nullability for computed and
// LATERAL-joined columns; the Go side uses is_prefix to pick the meaningful
// fields per row, so the placeholder values for the other branch are ignored.
func (q *Queries) ListObjectsDelimited(ctx context.Context, arg ListObjectsDelimitedParams) ([]ListObjectsDelimitedRow, error) {
	rows, err := q.db.Query(ctx, listObjectsDelimited,
		arg.Prefix,
		arg.Delim,
		arg.Lim,
		arg.Escprefix,
		arg.StartAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsDelimitedRow{}
	for rows.Next() {
		var i ListObjectsDelimitedRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.IsPrefix,
			&i.CommonPrefix,
			&i.SkipBound,
			&i.BackendName,
			&i.SizeBytes,
			&i.Etag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncompressedLocations = `-- name: ListUncompressedLocations :many
SELECT object_key, backend_name, storage_key, size_bytes, encrypted, encryption_key, key_id,
       plaintext_size, compression_algorithm, compression_level,
       compression_format_version, logical_size, etag
FROM object_locations
WHERE compression_algorithm IS NULL
  AND ($1::text = '' OR backend_name = $1::text)
  AND (CASE WHEN encrypted THEN plaintext_size ELSE size_bytes END) >= $2::bigint
  AND (compression_probe_size IS NULL
       OR compression_probe_level IS DISTINCT FROM $3::text
       OR compression_probe_size::float8
          / NULLIF(CASE WHEN encrypted THEN plaintext_size ELSE size_bytes END, 0)::float8
          <= $4::float8)
  AND (object_key, backend_name) > ($5::text, $6::text)
ORDER BY object_key, backend_name
LIMIT $7
`

type ListUncompressedLocationsParams struct {
	BackendFilter string
	MinSize       int64
	ProbeLevel    string
	MinRatio      float64
	AfterKey      string
	AfterBackend  string
	RowLimit      int32
}

type ListUncompressedLocationsRow struct {
	ObjectKey                string
	BackendName              string
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	Etag                     *string
}

// Copies whose stored bytes carry no encoding, which is what compress-existing
// rewrites. The encryption columns come along because compression sits inside
// encryption: an encrypted copy is decrypted, encoded, and re-encrypted under
// the key it already had.
//
// Paged by cursor, not offset: an encoded copy leaves this predicate, so the
// set shrinks under the pass walking it.
//
// Copies already measured as not worth encoding are excluded here rather than
// downloaded and encoded again to reach the same verdict, which on an
// incompressible fleet is the pass's largest wasted expense. The stored
// measurement is judged against the current settings, so it excludes a copy
// only while it would still be declined: lowering min_ratio returns those
// copies to the pass without reading any of them. A probe taken at a different
// level says nothing about this one and is ignored, since the levels are names
// from an ordered set rather than numbers.
//
// The divisor is NULLIF'd because a zero-length copy cannot shrink: the
// comparison goes NULL and the row is excluded, matching WorthStoring, which
// declines a logical size of zero outright.
//
// The size floor is applied here for the same reason, one the row can answer:
// a copy below it is never a candidate, so listing it only to decline it costs
// a page slot on every pass forever.
func (q *Queries) ListUncompressedLocations(ctx context.Context, arg ListUncompressedLocationsParams) ([]ListUncompressedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listUncompressedLocations,
		arg.BackendFilter,
		arg.MinSize,
		arg.ProbeLevel,
		arg.MinRatio,
		arg.AfterKey,
		arg.AfterBackend,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUncompressedLocationsRow{}
	for rows.Next() {
		var i ListUncompressedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CompressionAlgorithm,
			&i.CompressionLevel,
			&i.CompressionFormatVersion,
			&i.LogicalSize,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnencryptedLocations = `-- name: ListUnencryptedLocations :many
SELECT object_key, backend_name, storage_key, size_bytes, etag
FROM object_locations
WHERE encrypted = FALSE
  AND ($1::text = '' OR backend_name = $1::text)
  AND (object_key, backend_name) > ($2::text, $3::text)
ORDER BY object_key, backend_name
LIMIT $4
`

type ListUnencryptedLocationsParams struct {
	BackendFilter string
	AfterKey      string
	AfterBackend  string
	RowLimit      int32
}

type ListUnencryptedLocationsRow struct {
	ObjectKey   string
	BackendName string
	StorageKey  string
	SizeBytes   int64
	Etag        *string
}

// Paged by cursor rather than offset. Encrypting a copy takes it out of this
// predicate, so the set shrinks as encrypt-existing walks it and an offset
// would step over the rows that moved up.
//
// An empty backend_filter selects every backend, which is what a pass over the
// whole fleet asks for. Filtering here rather than after the page is read is
// what keeps the row_limit spent on candidates the pass will act on.
func (q *Queries) ListUnencryptedLocations(ctx context.Context, arg ListUnencryptedLocationsParams) ([]ListUnencryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listUnencryptedLocations,
		arg.BackendFilter,
		arg.AfterKey,
		arg.AfterBackend,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnencryptedLocationsRow{}
	for rows.Next() {
		var i ListUnencryptedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockObjectKeyForWrite = `-- name: LockObjectKeyForWrite :exec

SELECT pg_advisory_xact_lock(hashtext($1))
`

// -----------------------------------------------------------------------------
// Object Location Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for object_locations - the canonical (object_key,
// backend_name) ledger of which backends hold which objects. Includes the
// transactional advisory lock primitive (LockObjectKeyForWrite) used by the
// write path, the FOR UPDATE locks used by the per-key transactional helpers
// in core/, and the listing queries the manager and dashboard consume.
// -----------------------------------------------------------------------------
func (q *Queries) LockObjectKeyForWrite(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, lockObjectKeyForWrite, hashtext)
	return err
}

const lockObjectOnBackend = `-- name: LockObjectOnBackend :one
SELECT storage_key, size_bytes, encrypted, encryption_key, key_id, plaintext_size, content_hash,
       compression_algorithm, compression_level, compression_format_version, logical_size,
       compression_probe_size, compression_probe_level, etag, content_type, user_metadata
FROM object_locations
WHERE object_key = $1 AND backend_name = $2
FOR UPDATE
`

type LockObjectOnBackendParams struct {
	ObjectKey   string
	BackendName string
}

type LockObjectOnBackendRow struct {
	StorageKey               string
	SizeBytes                int64
	Encrypted                bool
	EncryptionKey            []byte
	KeyID                    *string
	PlaintextSize            *int64
	ContentHash              *string
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	CompressionProbeSize     *int64
	CompressionProbeLevel    *string
	Etag                     *string
	ContentType              *string
	UserMetadata             []byte
}

// Every column describing the stored bytes, because the caller moving this row
// to another backend rebuilds the destination from what this returns. A column
// missing here is one the moved copy silently stops claiming, which for the
// compression columns means a still-encoded object recorded as verbatim.
//
// The probe columns come along because a verbatim move does not change the
// bytes, so what the encoder measured about them still holds. Dropping them
// would have the next pass download and encode the copy again to learn what
// this row already knows.
func (q *Queries) LockObjectOnBackend(ctx context.Context, arg LockObjectOnBackendParams) (LockObjectOnBackendRow, error) {
	row := q.db.QueryRow(ctx, lockObjectOnBackend, arg.ObjectKey, arg.BackendName)
	var i LockObjectOnBackendRow
	err := row.Scan(
		&i.StorageKey,
		&i.SizeBytes,
		&i.Encrypted,
		&i.EncryptionKey,
		&i.KeyID,
		&i.PlaintextSize,
		&i.ContentHash,
		&i.CompressionAlgorithm,
		&i.CompressionLevel,
		&i.CompressionFormatVersion,
		&i.LogicalSize,
		&i.CompressionProbeSize,
		&i.CompressionProbeLevel,
		&i.Etag,
		&i.ContentType,
		&i.UserMetadata,
	)
	return i, err
}

const markObjectCompressed = `-- name: MarkObjectCompressed :execrows
UPDATE object_locations
SET compression_algorithm = $3,
    compression_level = $4,
    compression_format_version = $5,
    logical_size = $6,
    size_bytes = $7,
    plaintext_size = $8,
    encryption_key = $9,
    key_id = $10
WHERE object_key = $1 AND backend_name = $2
  AND etag IS NOT DISTINCT FROM $11::text
`

type MarkObjectCompressedParams struct {
	ObjectKey                string
	BackendName              string
	CompressionAlgorithm     *string
	CompressionLevel         *string
	CompressionFormatVersion *int16
	LogicalSize              *int64
	SizeBytes                int64
	PlaintextSize            *int64
	EncryptionKey            []byte
	KeyID                    *string
	ExpectedEtag             *string
}

// Records how a rewritten copy is now stored. A NULL algorithm is the
// decompress direction, which also clears the columns that only describe an
// encoding. The envelope columns are rewritten too: re-encrypting an object
// mints a new base nonce and wrapped key, so leaving the old ones would
// describe bytes nothing can decrypt.
//
// Committed only while the row still reports the etag the transform read. A
// client writing the key mid-pass changes it, and the bytes this would describe
// are then no longer the bytes stored - so no row matches and the caller skips
// the copy. IS NOT DISTINCT FROM rather than =, so a row that carried no etag
// and gained one from a client write fails the check instead of matching NULL.
func (q *Queries) MarkObjectCompressed(ctx context.Context, arg MarkObjectCompressedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markObjectCompressed,
		arg.ObjectKey,
		arg.BackendName,
		arg.CompressionAlgorithm,
		arg.CompressionLevel,
		arg.CompressionFormatVersion,
		arg.LogicalSize,
		arg.SizeBytes,
		arg.PlaintextSize,
		arg.EncryptionKey,
		arg.KeyID,
		arg.ExpectedEtag,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markObjectDecrypted = `-- name: MarkObjectDecrypted :execrows
UPDATE object_locations
SET encrypted = FALSE,
    encryption_key = NULL,
    key_id = NULL,
    size_bytes = $3,
    plaintext_size = NULL
WHERE object_key = $1 AND backend_name = $2
  AND etag IS NOT DISTINCT FROM $4::text
`

type MarkObjectDecryptedParams struct {
	ObjectKey    string
	BackendName  string
	SizeBytes    int64
	ExpectedEtag *string
}

// Committed only while the row still reports the etag the transform read. A
// client writing the key mid-pass changes it, and the bytes this would describe
// are then no longer the bytes stored - so no row matches and the caller skips
// the copy. IS NOT DISTINCT FROM rather than =, so a row that carried no etag
// and gained one from a client write fails the check instead of matching NULL.
func (q *Queries) MarkObjectDecrypted(ctx context.Context, arg MarkObjectDecryptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markObjectDecrypted,
		arg.ObjectKey,
		arg.BackendName,
		arg.SizeBytes,
		arg.ExpectedEtag,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markObjectEncrypted = `-- name: MarkObjectEncrypted :execrows
UPDATE object_locations
SET encrypted = TRUE,
    encryption_key = $3,
    key_id = $4,
    plaintext_size = $5,
    size_bytes = $6
WHERE object_key = $1 AND backend_name = $2
  AND etag IS NOT DISTINCT FROM $7::text
`

type MarkObjectEncryptedParams struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	SizeBytes     int64
	ExpectedEtag  *string
}

// Committed only while the row still reports the etag the transform read. A
// client writing the key mid-pass changes it, and the bytes this would describe
// are then no longer the bytes stored - so no row matches and the caller skips
// the copy. IS NOT DISTINCT FROM rather than =, so a row that carried no etag
// and gained one from a client write fails the check instead of matching NULL.
func (q *Queries) MarkObjectEncrypted(ctx context.Context, arg MarkObjectEncryptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markObjectEncrypted,
		arg.ObjectKey,
		arg.BackendName,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.SizeBytes,
		arg.ExpectedEtag,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markObjectScrubbed = `-- name: MarkObjectScrubbed :exec
UPDATE object_locations
SET last_scrubbed_at = NOW()
WHERE object_key = $1 AND backend_name = $2
`

type MarkObjectScrubbedParams struct {
	ObjectKey   string
	BackendName string
}

// Stamp a copy the scrubber just examined. Applied to every attempted copy,
// not only the ones that verified: a copy that cannot be read would otherwise
// stay at the head of the queue and starve the rest of the sweep.
func (q *Queries) MarkObjectScrubbed(ctx context.Context, arg MarkObjectScrubbedParams) error {
	_, err := q.db.Exec(ctx, markObjectScrubbed, arg.ObjectKey, arg.BackendName)
	return err
}

const recordCompressionProbe = `-- name: RecordCompressionProbe :exec
UPDATE object_locations
SET compression_probe_size = $3,
    compression_probe_level = $4
WHERE object_key = $1 AND backend_name = $2
`

type RecordCompressionProbeParams struct {
	ObjectKey             string
	BackendName           string
	CompressionProbeSize  *int64
	CompressionProbeLevel *string
}

// Records what the encoder produced for a copy it declined to store compressed,
// so the next pass reaches the same verdict from the row instead of downloading
// and encoding the object again.
//
// Only the min_ratio decline writes here. A min_size decline is answered from
// the row at no cost, a copy declined by usage limits never reached the encoder,
// and a failure measured nothing.
func (q *Queries) RecordCompressionProbe(ctx context.Context, arg RecordCompressionProbeParams) error {
	_, err := q.db.Exec(ctx, recordCompressionProbe,
		arg.ObjectKey,
		arg.BackendName,
		arg.CompressionProbeSize,
		arg.CompressionProbeLevel,
	)
	return err
}

const recordObjectIdentity = `-- name: RecordObjectIdentity :exec
UPDATE object_locations
SET etag          = COALESCE(etag, $2),
    content_type  = COALESCE(content_type, $3),
    user_metadata = COALESCE(user_metadata, $4)
WHERE object_key = $1
`

type RecordObjectIdentityParams struct {
	ObjectKey    string
	Etag         *string
	ContentType  *string
	UserMetadata []byte
}

// RecordObjectIdentity fills in what a read had to ask a backend for, so the
// next one does not. Every copy of the key is written, not just the one that
// answered: a per-copy value is what lets a failover change the ETag under a
// conditional request, which is the divergence this column exists to end.
//
// Only NULL columns are filled. A recorded identity is what the write computed
// over the client's own bytes, and a backend's answer must never overwrite it.
func (q *Queries) RecordObjectIdentity(ctx context.Context, arg RecordObjectIdentityParams) error {
	_, err := q.db.Exec(ctx, recordObjectIdentity,
		arg.ObjectKey,
		arg.Etag,
		arg.ContentType,
		arg.UserMetadata,
	)
	return err
}

const updateContentHash = `-- name: UpdateContentHash :exec
UPDATE object_locations
SET content_hash = $3, last_scrubbed_at = NOW()
WHERE object_key = $1 AND backend_name = $2
`

type UpdateContentHashParams struct {
	ObjectKey   string
	BackendName string
	ContentHash *string
}

// Record the hash the backfill pass computed and stamp the copy as verified in
// the same statement. The pass read the whole body to produce the digest, so the
// copy is verified by construction at that moment. Leaving last_scrubbed_at NULL
// would report it as never verified and sort it to the head of the scrub queue
// on its original created_at, so the next sweep would re-read the same bytes.
func (q *Queries) UpdateContentHash(ctx context.Context, arg UpdateContentHashParams) error {
	_, err := q.db.Exec(ctx, updateContentHash, arg.ObjectKey, arg.BackendName, arg.ContentHash)
	return err
}

const updateEncryptionKey = `-- name: UpdateEncryptionKey :exec
UPDATE object_locations
SET encryption_key = $3, key_id = $4
WHERE object_key = $1 AND backend_name = $2
`

type UpdateEncryptionKeyParams struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
}

func (q *Queries) UpdateEncryptionKey(ctx context.Context, arg UpdateEncryptionKeyParams) error {
	_, err := q.db.Exec(ctx, updateEncryptionKey,
		arg.ObjectKey,
		arg.BackendName,
		arg.EncryptionKey,
		arg.KeyID,
	)
	return err
}
