// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/proxy/writepath (interfaces: CoordinatorStores)
//
// Generated by this command:
//
//	mockgen -destination=mock_stores_test.go -package=writepath github.com/afreidah/s3-orchestrator/internal/proxy/writepath CoordinatorStores
//

// Package writepath is a generated GoMock package.
package writepath

import (
	context "context"
	reflect "reflect"
	time "time"

	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	gomock "go.uber.org/mock/gomock"
)

// MockCoordinatorStores is a mock of CoordinatorStores interface.
type MockCoordinatorStores struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorStoresMockRecorder
	isgomock struct{}
}

// MockCoordinatorStoresMockRecorder is the mock recorder for MockCoordinatorStores.
type MockCoordinatorStoresMockRecorder struct {
	mock *MockCoordinatorStores
}

// NewMockCoordinatorStores creates a new mock instance.
func NewMockCoordinatorStores(ctrl *gomock.Controller) *MockCoordinatorStores {
	mock := &MockCoordinatorStores{ctrl: ctrl}
	mock.recorder = &MockCoordinatorStoresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinatorStores) EXPECT() *MockCoordinatorStoresMockRecorder {
	return m.recorder
}

// ClaimPendingCleanups mocks base method.
func (m *MockCoordinatorStores) ClaimPendingCleanups(ctx context.Context, limit int, instanceID string, graceCutoff time.Time) ([]core.CleanupItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingCleanups", ctx, limit, instanceID, graceCutoff)
	ret0, _ := ret[0].([]core.CleanupItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingCleanups indicates an expected call of ClaimPendingCleanups.
func (mr *MockCoordinatorStoresMockRecorder) ClaimPendingCleanups(ctx, limit, instanceID, graceCutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingCleanups", reflect.TypeOf((*MockCoordinatorStores)(nil).ClaimPendingCleanups), ctx, limit, instanceID, graceCutoff)
}

// CleanupDLQDepth mocks base method.
func (m *MockCoordinatorStores) CleanupDLQDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupDLQDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupDLQDepth indicates an expected call of CleanupDLQDepth.
func (mr *MockCoordinatorStoresMockRecorder) CleanupDLQDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupDLQDepth", reflect.TypeOf((*MockCoordinatorStores)(nil).CleanupDLQDepth), ctx)
}

// CleanupQueueDepth mocks base method.
func (m *MockCoordinatorStores) CleanupQueueDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupQueueDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupQueueDepth indicates an expected call of CleanupQueueDepth.
func (mr *MockCoordinatorStoresMockRecorder) CleanupQueueDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupQueueDepth", reflect.TypeOf((*MockCoordinatorStores)(nil).CleanupQueueDepth), ctx)
}

// CommitCompanionCopy mocks base method.
func (m *MockCoordinatorStores) CommitCompanionCopy(ctx context.Context, p *core.PendingObject) (core.CompanionCommitResult, []core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitCompanionCopy", ctx, p)
	ret0, _ := ret[0].(core.CompanionCommitResult)
	ret1, _ := ret[1].([]core.DeletedCopy)
	ret2, _ := ret[2].(core.QuotaDeltas)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CommitCompanionCopy indicates an expected call of CommitCompanionCopy.
func (mr *MockCoordinatorStoresMockRecorder) CommitCompanionCopy(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitCompanionCopy", reflect.TypeOf((*MockCoordinatorStores)(nil).CommitCompanionCopy), ctx, p)
}

// CompleteCleanupItem mocks base method.
func (m *MockCoordinatorStores) CompleteCleanupItem(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCleanupItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteCleanupItem indicates an expected call of CompleteCleanupItem.
func (mr *MockCoordinatorStoresMockRecorder) CompleteCleanupItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCleanupItem", reflect.TypeOf((*MockCoordinatorStores)(nil).CompleteCleanupItem), ctx, id)
}

// CountObjectsByPrefix mocks base method.
func (m *MockCoordinatorStores) CountObjectsByPrefix(ctx context.Context, prefix string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountObjectsByPrefix", ctx, prefix)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountObjectsByPrefix indicates an expected call of CountObjectsByPrefix.
func (mr *MockCoordinatorStoresMockRecorder) CountObjectsByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountObjectsByPrefix", reflect.TypeOf((*MockCoordinatorStores)(nil).CountObjectsByPrefix), ctx, prefix)
}

// DecrementOrphanBytes mocks base method.
func (m *MockCoordinatorStores) DecrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementOrphanBytes indicates an expected call of DecrementOrphanBytes.
func (mr *MockCoordinatorStoresMockRecorder) DecrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementOrphanBytes", reflect.TypeOf((*MockCoordinatorStores)(nil).DecrementOrphanBytes), ctx, backendName, amount)
}

// DeleteObject mocks base method.
func (m *MockCoordinatorStores) DeleteObject(ctx context.Context, key string) ([]core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(core.QuotaDeltas)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockCoordinatorStoresMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockCoordinatorStores)(nil).DeleteObject), ctx, key)
}

// DeleteObjectLocation mocks base method.
func (m *MockCoordinatorStores) DeleteObjectLocation(ctx context.Context, key, backendName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectLocation", ctx, key, backendName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectLocation indicates an expected call of DeleteObjectLocation.
func (mr *MockCoordinatorStoresMockRecorder) DeleteObjectLocation(ctx, key, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectLocation", reflect.TypeOf((*MockCoordinatorStores)(nil).DeleteObjectLocation), ctx, key, backendName)
}

// DeleteObjectsBatch mocks base method.
func (m *MockCoordinatorStores) DeleteObjectsBatch(ctx context.Context, keys []string) (map[string][]core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectsBatch", ctx, keys)
	ret0, _ := ret[0].(map[string][]core.DeletedCopy)
	ret1, _ := ret[1].(core.QuotaDeltas)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteObjectsBatch indicates an expected call of DeleteObjectsBatch.
func (mr *MockCoordinatorStoresMockRecorder) DeleteObjectsBatch(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectsBatch", reflect.TypeOf((*MockCoordinatorStores)(nil).DeleteObjectsBatch), ctx, keys)
}

// DeletePending mocks base method.
func (m *MockCoordinatorStores) DeletePending(ctx context.Context, intentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePending", ctx, intentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePending indicates an expected call of DeletePending.
func (mr *MockCoordinatorStoresMockRecorder) DeletePending(ctx, intentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePending", reflect.TypeOf((*MockCoordinatorStores)(nil).DeletePending), ctx, intentID)
}

// DeletePendingByBackend mocks base method.
func (m *MockCoordinatorStores) DeletePendingByBackend(ctx context.Context, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingByBackend", ctx, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingByBackend indicates an expected call of DeletePendingByBackend.
func (mr *MockCoordinatorStoresMockRecorder) DeletePendingByBackend(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingByBackend", reflect.TypeOf((*MockCoordinatorStores)(nil).DeletePendingByBackend), ctx, backendName)
}

// EnqueueCleanup mocks base method.
func (m *MockCoordinatorStores) EnqueueCleanup(ctx context.Context, c *core.CleanupRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueCleanup", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueCleanup indicates an expected call of EnqueueCleanup.
func (mr *MockCoordinatorStoresMockRecorder) EnqueueCleanup(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueCleanup", reflect.TypeOf((*MockCoordinatorStores)(nil).EnqueueCleanup), ctx, c)
}

// GetAllObjectLocations mocks base method.
func (m *MockCoordinatorStores) GetAllObjectLocations(ctx context.Context, key string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjectLocations", ctx, key)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllObjectLocations indicates an expected call of GetAllObjectLocations.
func (mr *MockCoordinatorStoresMockRecorder) GetAllObjectLocations(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjectLocations", reflect.TypeOf((*MockCoordinatorStores)(nil).GetAllObjectLocations), ctx, key)
}

// GetObjectBackendsForKeys mocks base method.
func (m *MockCoordinatorStores) GetObjectBackendsForKeys(ctx context.Context, keys []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectBackendsForKeys", ctx, keys)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectBackendsForKeys indicates an expected call of GetObjectBackendsForKeys.
func (mr *MockCoordinatorStoresMockRecorder) GetObjectBackendsForKeys(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectBackendsForKeys", reflect.TypeOf((*MockCoordinatorStores)(nil).GetObjectBackendsForKeys), ctx, keys)
}

// GetPendingCleanups mocks base method.
func (m *MockCoordinatorStores) GetPendingCleanups(ctx context.Context, limit int) ([]core.CleanupItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingCleanups", ctx, limit)
	ret0, _ := ret[0].([]core.CleanupItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingCleanups indicates an expected call of GetPendingCleanups.
func (mr *MockCoordinatorStoresMockRecorder) GetPendingCleanups(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingCleanups", reflect.TypeOf((*MockCoordinatorStores)(nil).GetPendingCleanups), ctx, limit)
}

// GetQuotaStats mocks base method.
func (m *MockCoordinatorStores) GetQuotaStats(ctx context.Context) (map[string]core.QuotaStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaStats", ctx)
	ret0, _ := ret[0].(map[string]core.QuotaStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaStats indicates an expected call of GetQuotaStats.
func (mr *MockCoordinatorStoresMockRecorder) GetQuotaStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaStats", reflect.TypeOf((*MockCoordinatorStores)(nil).GetQuotaStats), ctx)
}

// GetStalePending mocks base method.
func (m *MockCoordinatorStores) GetStalePending(ctx context.Context, olderThan time.Time, limit int) ([]core.PendingObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStalePending", ctx, olderThan, limit)
	ret0, _ := ret[0].([]core.PendingObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStalePending indicates an expected call of GetStalePending.
func (mr *MockCoordinatorStoresMockRecorder) GetStalePending(ctx, olderThan, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStalePending", reflect.TypeOf((*MockCoordinatorStores)(nil).GetStalePending), ctx, olderThan, limit)
}

// ImportObject mocks base method.
func (m *MockCoordinatorStores) ImportObject(ctx context.Context, req *core.ImportObjectRequest) (core.ImportOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportObject", ctx, req)
	ret0, _ := ret[0].(core.ImportOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportObject indicates an expected call of ImportObject.
func (mr *MockCoordinatorStoresMockRecorder) ImportObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportObject", reflect.TypeOf((*MockCoordinatorStores)(nil).ImportObject), ctx, req)
}

// IncrementOrphanBytes mocks base method.
func (m *MockCoordinatorStores) IncrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOrphanBytes indicates an expected call of IncrementOrphanBytes.
func (mr *MockCoordinatorStoresMockRecorder) IncrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOrphanBytes", reflect.TypeOf((*MockCoordinatorStores)(nil).IncrementOrphanBytes), ctx, backendName, amount)
}

// InsertPendingIfFits mocks base method.
func (m *MockCoordinatorStores) InsertPendingIfFits(ctx context.Context, p *core.PendingObject) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPendingIfFits", ctx, p)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPendingIfFits indicates an expected call of InsertPendingIfFits.
func (mr *MockCoordinatorStoresMockRecorder) InsertPendingIfFits(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPendingIfFits", reflect.TypeOf((*MockCoordinatorStores)(nil).InsertPendingIfFits), ctx, p)
}

// ListBackendQuotaUsage mocks base method.
func (m *MockCoordinatorStores) ListBackendQuotaUsage(ctx context.Context) ([]core.BackendQuotaUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackendQuotaUsage", ctx)
	ret0, _ := ret[0].([]core.BackendQuotaUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackendQuotaUsage indicates an expected call of ListBackendQuotaUsage.
func (mr *MockCoordinatorStoresMockRecorder) ListBackendQuotaUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackendQuotaUsage", reflect.TypeOf((*MockCoordinatorStores)(nil).ListBackendQuotaUsage), ctx)
}

// ListCleanupDLQ mocks base method.
func (m *MockCoordinatorStores) ListCleanupDLQ(ctx context.Context, backend string, limit int) ([]core.CleanupDLQItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCleanupDLQ", ctx, backend, limit)
	ret0, _ := ret[0].([]core.CleanupDLQItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCleanupDLQ indicates an expected call of ListCleanupDLQ.
func (mr *MockCoordinatorStoresMockRecorder) ListCleanupDLQ(ctx, backend, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCleanupDLQ", reflect.TypeOf((*MockCoordinatorStores)(nil).ListCleanupDLQ), ctx, backend, limit)
}

// ListObjects mocks base method.
func (m *MockCoordinatorStores) ListObjects(ctx context.Context, prefix, startAfter string, maxKeys int) (*core.ListObjectsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListObjectsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockCoordinatorStoresMockRecorder) ListObjects(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockCoordinatorStores)(nil).ListObjects), ctx, prefix, startAfter, maxKeys)
}

// ListObjectsByBackend mocks base method.
func (m *MockCoordinatorStores) ListObjectsByBackend(ctx context.Context, backendName string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackend", ctx, backendName, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackend indicates an expected call of ListObjectsByBackend.
func (mr *MockCoordinatorStoresMockRecorder) ListObjectsByBackend(ctx, backendName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackend", reflect.TypeOf((*MockCoordinatorStores)(nil).ListObjectsByBackend), ctx, backendName, limit)
}

// ListObjectsByBackendKeyAsc mocks base method.
func (m *MockCoordinatorStores) ListObjectsByBackendKeyAsc(ctx context.Context, backendName, afterKey string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackendKeyAsc", ctx, backendName, afterKey, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackendKeyAsc indicates an expected call of ListObjectsByBackendKeyAsc.
func (mr *MockCoordinatorStoresMockRecorder) ListObjectsByBackendKeyAsc(ctx, backendName, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackendKeyAsc", reflect.TypeOf((*MockCoordinatorStores)(nil).ListObjectsByBackendKeyAsc), ctx, backendName, afterKey, limit)
}

// ListObjectsDelimited mocks base method.
func (m *MockCoordinatorStores) ListObjectsDelimited(ctx context.Context, prefix, delimiter, startAfter string, maxKeys int) (*core.ListDelimitedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsDelimited", ctx, prefix, delimiter, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListDelimitedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsDelimited indicates an expected call of ListObjectsDelimited.
func (mr *MockCoordinatorStoresMockRecorder) ListObjectsDelimited(ctx, prefix, delimiter, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsDelimited", reflect.TypeOf((*MockCoordinatorStores)(nil).ListObjectsDelimited), ctx, prefix, delimiter, startAfter, maxKeys)
}

// MoveCleanupToDLQ mocks base method.
func (m *MockCoordinatorStores) MoveCleanupToDLQ(ctx context.Context, id int64, lastError string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveCleanupToDLQ", ctx, id, lastError)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveCleanupToDLQ indicates an expected call of MoveCleanupToDLQ.
func (mr *MockCoordinatorStoresMockRecorder) MoveCleanupToDLQ(ctx, id, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveCleanupToDLQ", reflect.TypeOf((*MockCoordinatorStores)(nil).MoveCleanupToDLQ), ctx, id, lastError)
}

// MoveObjectLocation mocks base method.
func (m_2 *MockCoordinatorStores) MoveObjectLocation(ctx context.Context, m *core.MoveLocation) (int64, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MoveObjectLocation", ctx, m)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveObjectLocation indicates an expected call of MoveObjectLocation.
func (mr *MockCoordinatorStoresMockRecorder) MoveObjectLocation(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveObjectLocation", reflect.TypeOf((*MockCoordinatorStores)(nil).MoveObjectLocation), ctx, m)
}

// PendingDepth mocks base method.
func (m *MockCoordinatorStores) PendingDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingDepth indicates an expected call of PendingDepth.
func (mr *MockCoordinatorStoresMockRecorder) PendingDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingDepth", reflect.TypeOf((*MockCoordinatorStores)(nil).PendingDepth), ctx)
}

// PromotePending mocks base method.
func (m *MockCoordinatorStores) PromotePending(ctx context.Context, p *core.PendingObject) (core.PendingPromoteResult, []core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromotePending", ctx, p)
	ret0, _ := ret[0].(core.PendingPromoteResult)
	ret1, _ := ret[1].([]core.DeletedCopy)
	ret2, _ := ret[2].(core.QuotaDeltas)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// PromotePending indicates an expected call of PromotePending.
func (mr *MockCoordinatorStoresMockRecorder) PromotePending(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromotePending", reflect.TypeOf((*MockCoordinatorStores)(nil).PromotePending), ctx, p)
}

// ReconcileUsage mocks base method.
func (m *MockCoordinatorStores) ReconcileUsage(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileUsage", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileUsage indicates an expected call of ReconcileUsage.
func (mr *MockCoordinatorStoresMockRecorder) ReconcileUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileUsage", reflect.TypeOf((*MockCoordinatorStores)(nil).ReconcileUsage), ctx)
}

// RecordObject mocks base method.
func (m *MockCoordinatorStores) RecordObject(ctx context.Context, req *core.RecordObjectRequest) ([]core.DeletedCopy, core.QuotaDeltas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordObject", ctx, req)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(core.QuotaDeltas)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecordObject indicates an expected call of RecordObject.
func (mr *MockCoordinatorStoresMockRecorder) RecordObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordObject", reflect.TypeOf((*MockCoordinatorStores)(nil).RecordObject), ctx, req)
}

// RecordObjectIdentity mocks base method.
func (m *MockCoordinatorStores) RecordObjectIdentity(ctx context.Context, key string, id *core.ObjectIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordObjectIdentity", ctx, key, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordObjectIdentity indicates an expected call of RecordObjectIdentity.
func (mr *MockCoordinatorStoresMockRecorder) RecordObjectIdentity(ctx, key, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordObjectIdentity", reflect.TypeOf((*MockCoordinatorStores)(nil).RecordObjectIdentity), ctx, key, id)
}

// RequeueCleanupDLQ mocks base method.
func (m *MockCoordinatorStores) RequeueCleanupDLQ(ctx context.Context, backend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueCleanupDLQ", ctx, backend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequeueCleanupDLQ indicates an expected call of RequeueCleanupDLQ.
func (mr *MockCoordinatorStoresMockRecorder) RequeueCleanupDLQ(ctx, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueCleanupDLQ", reflect.TypeOf((*MockCoordinatorStores)(nil).RequeueCleanupDLQ), ctx, backend)
}

// RetryCleanupItem mocks base method.
func (m *MockCoordinatorStores) RetryCleanupItem(ctx context.Context, id int64, backoff time.Duration, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryCleanupItem", ctx, id, backoff, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryCleanupItem indicates an expected call of RetryCleanupItem.
func (mr *MockCoordinatorStoresMockRecorder) RetryCleanupItem(ctx, id, backoff, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryCleanupItem", reflect.TypeOf((*MockCoordinatorStores)(nil).RetryCleanupItem), ctx, id, backoff, lastError)
}

// SweepStaleCleanupQueueRows mocks base method.
func (m *MockCoordinatorStores) SweepStaleCleanupQueueRows(ctx context.Context, storageKey, backend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepStaleCleanupQueueRows", ctx, storageKey, backend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepStaleCleanupQueueRows indicates an expected call of SweepStaleCleanupQueueRows.
func (mr *MockCoordinatorStoresMockRecorder) SweepStaleCleanupQueueRows(ctx, storageKey, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepStaleCleanupQueueRows", reflect.TypeOf((*MockCoordinatorStores)(nil).SweepStaleCleanupQueueRows), ctx, storageKey, backend)
}
